### ISSUE TITLE
pull-image-builder-test workflow doesn't work

### ISSUE THREAD

**Issue by Sawthis** [kyma-project/test-infra#11614]
**Description**

I've tried to test [pull-image-builder-test](https://github.com/kyma-project/test-infra/blob/main/.github/workflows/pull-image-builder-test.yml) workflow in the https://github.com/kyma-project/test-infra/pull/11608 and it [failed](https://github.com/kyma-project/test-infra/actions/runs/10298467450/workflow).

**Expected result**

pull-image-builder-test workflow should work when it is triggered in the pull request.

**Actual result**

pull-image-builder-test workflow fails when it is triggered in the pull request.

**Steps to reproduce**

Open the pull request like https://github.com/kyma-project/test-infra/pull/11608.

**Troubleshooting**

Check the commits in the https://github.com/kyma-project/test-infra/pull/11608

**Comment by dekiel** [comment]
We can't checkout pull request head in the same job where we call an image-builder reusable workflow. Github actions allows only subset of syntax keywords in a job which uses a reusable workflow. Keywords `steps` and `runs-on` are not allowed. This makes impossible to call a checkout step before calling reusable workflow. See GitHub docs https://docs.github.com/en/actions/sharing-automations/reusing-workflows#supported-keywords-for-jobs-that-call-a-reusable-workflow

**Comment by dekiel** [comment]
Changed `pull-image-builder-test` workflow to use syntax which uses a reusable workflow from pull request which trigger the workflow run.
From https://docs.github.com/en/actions/sharing-automations/reusing-workflows#calling-a-reusable-workflow

> If you use the second syntax option (without {owner}/{repo} and @{ref}) the called workflow is from the same commit as the caller workflow. Ref prefixes such as refs/heads and refs/tags are not allowed.

After merging the changes in workflow to the main branch and creating a PR with changes in calling and reusable workflow https://github.com/kyma-project/test-infra/pull/11657, the changes are not used in workflow runs. https://github.com/kyma-project/test-infra/actions/runs/10421278183/job/28863146736?pr=11657

This is caused by using a `pull_request_target` event to trigger calling workflow. As we learned earlier, using a pull_request_target event is mandator to get an oidc token from github identity provider. The token is required to is required to authenticate in `oci-image-builder` ado pipeline.

**Conclusion**

It's not possible to test changes in resuable workflow by calling it's version from pull request in full integration test scenario. We must develop and define a way of testing image-builder application. See #11238
