### ISSUE TITLE
GKE Jobs are failing with: "is not valid for Network" error

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/test-infra#1173]
**Description**

Prow Jobs (presubmits, postsubmits) are failing with the following error:
```
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=Subnetwork "projects/sap-kyma-prow-workloads/regions/europe-west4/subnetworks/gke-upgrade-commit-subnet" is not valid for Network "gke-upgrade-commit-net".
```

**Expected result**

No error

**Actual result**

Job fails

**Steps to reproduce**

Look for failed post-submit jobs prow status. Pre-submit jobs are also failing.

**Troubleshooting**
Workaround does not exist.

**Comment by Tomasz-Smelcerz-SAP** [comment]
See for example: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1143755654721179649

**Comment by strekm** [comment]
Also fails for pre-submit jobs: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/4617/pre-master-kyma-gke-upgrade/1143762323270275072

**Comment by kasiakepka** [comment]
When I was testing new project setup, all of the resources were created in europe-west3 region but due to quota limits we were forced to migrate everything to europe-west4 region. After migration new clusters and subnetworks were created in west4 and that caused a conflict/mismatch with already existing subnetworks in west3 region.  Unfortunately our pipelines do not verify whether subnet in given region exists.
