### ISSUE TITLE
Define how to gather and store quality metrics

### ISSUE THREAD

**Issue by clebs** [kyma-project/test-infra#1506]
**Description**
In order to be able to collect metrics for quality we need to setup a system that can store the metrics for later display.

**Acceptance**
- A storage is in place to save all metrics.
- We have a way to send metrics into the storage from different systems (e.g. CI/CD).
- We can query metrics.

**Comment by kasiakepka** [comment]
Yes, we should use https://github.com/prometheus/client_golang and [pushgateway](https://github.com/prometheus/pushgateway/blob/master/README.md)

**Comment by kasiakepka** [comment]
We should discuss architecture proposal with people working on Scraping Metrics from Octopus. 
This issue is related to https://github.com/kyma-project/kyma/issues/5484

**Comment by dekiel** [comment]
For long running cluster it was decided to use stackdriver to collect prometheus metrics.
We will have to work on collecting metrics from other sources and other components.
See issue #1623

**Comment by kasiakepka** [comment]
We are waiting also for final proposal from Borja and Michał Hudy. This topic is still discussed in SIG-Quality meeting.

**Comment by michal-hudy** [comment]
Regarding this:
> We have a way to send metrics into the storage from different systems (e.g. CI/CD).

I would like first to see a proposal that will describe how we would like to collect metrics before the implementation will be made.

Anyway, this issue doesn't mention what metrics and from we would like to collect, so it would be nice to update the Issue - it will be helpful during work on the proposal.

---

In case of `CI/CD`I think we should avoid external (outside of the pod) communication as much as possible, and we should do that more Prow way, so:
 - Jobs should produce artifacts with coverprofile, JUnit, and others.
 - Jobs are monitored by controller (https://github.com/kyma-project/test-infra/tree/master/development/prow-addons-ctrl-manager - our solution for sending notifications to slack with failed jobs)
 - When Job is finished, such controller should collect these artifacts (not all, just that needed for metrics) and push/expose "metrics" to Prometheus like service or simply ping services to collect metrics from artifacts (thanks to that controller will be generic and lightweight).

In the case of "external" service like GitHub we can simply define a webhook to our service responsible for pushing/exposing metrics. If "external" service doesn't support webhooks, then we can create a CronJob that will pull expected information.

Anyway, as I said, I would like to see a proposal for this "system" before the implementation will be made.

**Comment by adamwalach** [comment]
Because every metric (code coverage, stats for github issues, failed tests per components)  is different it is hard to propose something that would satisfy all requirements.
My proposal is to use the simplest approach that we have already [tried](https://github.com/kyma-project/test-infra/issues/1798) - if we want to monitor a given metric, and we have a component that is putting required information in the logs - that is enough. Since all logs from our build and stability-testing infrastructure are gathered by StackDriver we can just create a data sink (export) and push the log line (it can contain JSON object) into BigQuery. 
Then it is just a matter of creating aggregation query, and we can create a report with charts in [DataStudio](https://datastudio.google.com/).

Advantages:
- tool that creates metric data is isolated from the database - it just prints text or a JSON string
- we can easily create metrics from information that are already available in logs ( i.e. stability checker errors: https://app.google.stackdriver.com/dashboards/10487706692048182495?project=sap-kyma-prow-workloads) 
- infrastructure is already in place - we only have to decide what needs to be gathered
- its cheap - [BigQuery](https://cloud.google.com/bigquery/pricing) is designed to handle datasets much bigger than ours
- we have first implementation up and running - https://datastudio.google.com/s/qCijKvXIN08

**Comment by adamwalach** [comment]
Docs: https://github.com/kyma-project/test-infra/blob/master/docs/prow/quality-metrics.md
