### ISSUE TITLE
Unit tests for generic prow job are not compatible with projects outside kyma-project and are overcomplicated

### ISSUE THREAD

**Issue by dbadura** [kyma-project/test-infra#1627]
**Description**
All `kyma-project` organization projects are in `prow` jobs directory. 
Currently all project from `kyma-incubator` are treated as `kyma-project` organization project.

Unit tests for new generic prow jobs are not compatible with projects outside `kyma-project` organization, because they are treated as `kyma-project` organization project.
Additionally generic unit tests for generic jobs are over-complicated.
Tests are hard to understand and `suite.Path` and `suite.Repository` variables are responsible for too many things.

**Expected result**
Jobs in `prow` directory should be separated by organization:
for example:
```
organization/project/component/
```

Unit tests should be easier to read and not overuse some variables.

**Actual result**
If you want to add unit tests for job which is not in `kyma-project` organization, it's not so easy.

**Steps to reproduce**

**Troubleshooting**

**Comment by mszostok** [comment]
I'm totally with you @dbadura but two cents from my side: 
- > Unit tests should be easier to read and not overuse some variables 
    
     IMO this is hard to implement, each person will have a different look on that. Who will review and accept the final solution? 

--- 
During the review I also posted some comment that
**My personal opinion**

I do not like magic :) 

having sth like `buildjob.NewSuite(opts...).Run(t)` is to magic. 
there is a lot of if statement inside. 

I will prefer to have more descriptive API and split it to sth like
```go
buildjob.NewPresubmitJobSuite(opts...).Run(t)
buildjob.NewPostsubmitJobSuite(opts...).Run(t)
buildjob.NewReleaseJobSuite(opts...).Run(t)

// or
suite := buildjob.NewSuite(opts...)
suite.TestPresubmitJobs(t)
suite.TestPostsubmitJobs(t)
suite.TestReleaseJobs(t)
```

source: https://github.com/kyma-project/test-infra/pull/1438#discussion_r321237509

**Summary**
so IMO you should come up with some ideas on how those tests should be refactored. As a result, people will know for what they are really voting and later on, someone can pick up this and implement it quite easily.

**Comment by dbadura** [comment]
I would create something like this
```go
job :=readJob(config)
assertPresubmitJob(job, cfg)
assertPostsubmitJob(job, cfg)
```

The config should consist of following options:
* repository (github.com)
* organization
* project
* component
and using those options, we can build the neeeded things in more readable way, without using `path` functions.

**Comment by sjanota** [comment]
Thumbs up regarding fixing the directory structure. We should also include file naming in the proposal as the job file names is the important part (they need to be globally unique). Directories are only for readability. I was also thinking some time ago about making the structure completely flat and put all the information in YAML name, ex. `kyma-project_kyma_components_console-backend-service.yaml`. It can't make up my mind though. It's not pretty at least 😄. 

As for the test API, the important thing for me is to check the dependencies between variables. That's why I think they should be roughly the same as the variables that the template accepts, but no strong opinion here.

Maybe I'll give an explanation of why `Path` is there. Let's see if it helps. I've added the `Path` property, so the test is not aware of the "type" of the component. The template itself knows nothing about "type". Why? Because the path is not always that obvious. For example, the console does not have a notion of "component".  Another example is `components/kubeless-images/nodejs` which also differs from other components. Take that into account while designing a new API.

**Comment by sjanota** [comment]
After giving it a second thought I'm not really sure why API for template and unit tests differ in this matter. I think I shouldn't have introduced the `Test`, `Component` and `Tool` functions, but rather enforce user to use the full path.

**Comment by dbadura** [comment]
1.
Flat structure is bad idea, because we will get disorder. It will be hard to find something.

2. Name of the job file can look like this:
`{organization}-{repository_name}-{component_name}`, but it's only a proposal.

3. Maybe `console` and `nodejs kubeless` images should be handled separately.
I think that file `suite.go` should be deleted, because it's contains only interface. It's not Java.

Removing `Path` functions is crucial for readbility and understanding what happening inside. 
```go
func (s ComponentSuite) jobName(prefix string) string {
	return fmt.Sprintf("%s-%s", prefix, s.moduleName())
}
```
the `moduleName()` func call another`repositoryName()` func which uses `path`. To many things happens when you want get the `jobName`

I think that func `Run` do too many things:
*create job path
*read the job
*asserting the job
*also creating some strange strings.

What do you think about buid test in the following way:
```
//GIVEN
cfg :=TestConfig(...) struct for things like repository name, component name and etc

//WHEN
testConfig := cfg.Build() - create job_name, needed keys and etc in one place
job :=ReadJob(testConfig)
//THEN
assertPreMaster(job, cfg) or runTestPreMaster(job, cfg)
... all assertions or all subtest launches.

**Comment by PK85** [comment]
Discussed with @dbadura and @adamwalach and no time to do that in upcoming months. I'm closing it.
