### ISSUE TITLE
Code Coverage POC

### ISSUE THREAD

**Issue by kasiakepka** [kyma-project/test-infra#1798]
This ticket is a response to the ad-hoc requirement reported on SIG Quality.

Here are information provided by Laurentiu:

Create Code Coverage 
- There are more and more issues coming from customers and an increasing concern about the quality of the product 
- The approach changed and it was decided to implement a code coverage tool already available on the market, but from my knowledge this tool was not chosen 
- Please do the next step of choosing the tool and estimating the complexity/time needed to integrate it, to be able to give it to a PO/team for implementation 
- We need to have this implemented by EoY

**Comment by adamwalach** [comment]
## Simple solution

The simplest approach to gather code coverage metrics is to get it directly from our build logs.
First step was done by @clebs but this change was lost when we migrated to a common Makefile solution. I brought it [back](https://github.com/kyma-project/kyma/pull/6449). 
Now in the logs of (almost) every job you can find "Total test coverage: xx%" string.

<img width="762" alt="Screen Shot 2019-12-03 at 10 29 42" src="https://user-images.githubusercontent.com/8530211/70041963-5c04a800-15be-11ea-9421-a9b7e8a854a2.png">

Since all logs from our build infrastructure are gathered by StackDriver we created "Export" (data sink) to filter out all these lines and send them to BigQuery:
<img width="1435" alt="Screen Shot 2019-12-03 at 11 22 39" src="https://user-images.githubusercontent.com/8530211/70042557-607d9080-15bf-11ea-9c69-d40f5b3bb3f7.png">

Now we have access to SQL, so we can create any report we want. For instance a comparison between last and previous test coverage:
```
SELECT
     distinct labels.k8s_pod_prow_k8s_io_job
   , FIRST_VALUE(CAST(REGEXP_EXTRACT(textPayload, r"(\d{1,2})") as int64))
       OVER w1 AS last_result
   , NTH_VALUE(CAST(REGEXP_EXTRACT(textPayload, r"(\d{1,2})") as int64),2)
       OVER w1 AS previous_result
   , FIRST_VALUE(timestamp)
       OVER w1 AS last_timestamp
   , NTH_VALUE(timestamp,2)
       OVER w1 AS previous_timestamp
   , format("https://status.build.kyma-project.io/?job=%s", labels.k8s_pod_prow_k8s_io_job)  as link
FROM `sap-kyma-prow.total_test_coverage.stdout`
  WINDOW w1 AS (
    PARTITION BY labels.k8s_pod_prow_k8s_io_job ORDER BY timestamp DESC
    ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)
order by 2 desc
```

This query can be used as a data source for a report created in DataStudio

<img width="1324" alt="Screen Shot 2019-12-03 at 11 28 20" src="https://user-images.githubusercontent.com/8530211/70042965-134dee80-15c0-11ea-97a5-4e9428105a09.png">

You can check this report here: https://datastudio.google.com/s/mK56WnUz778 (it is restricted to  Kyma development team)

Currently, this report shows data also from `pre` (pull request) jobs, so we should not pay too much attention to numbers yet. When we gather more  data (more `post` jobs will be executed) I'll change the query to only show `post` data.

## Using external services

We found two potential candidates:
- https://codecov.io/
- https://coveralls.io/

Both of them offer similar solutions.
We tested codecov.io in more detail and sent some data for one of Kyma components:
<img width="1176" alt="Screen Shot 2019-12-03 at 11 43 18" src="https://user-images.githubusercontent.com/8530211/70044989-a177a400-15c3-11ea-8c65-acf743cf9e01.png">
I will not go into details here, on codecov.io you can find pretty good docs and you can see few data points from my tests on cloned Kyma repo: https://codecov.io/gh/awalach-org/kyma

### Outcomes
My first assumption was that the only data we need in order to get a report on codecov is the cover.out file created in `go test` phase. It is stored in the [artifacts](https://gcsweb.build.kyma-project.io/gcs/kyma-prow-logs/logs/post-master-kyma-development-artifacts/1201801567871700993/artifacts/) directory in GCP bucket .
But as it turns out the package that is created by bash script provided by codecov.io also contains current sources. 
So, my idea was to create a simple script that would periodically go through a directory tree on a bucket and send all coverage reports (with some additional tags like commit SHA and some other data that can be extracted from json files created by prow) to codecov.io.  But we would have to also checkout to a commit for which the tests were performed. It's still possible but requires a bit more work.

I would advise against putting the upload script directly into our jobs.  This can make our pipelines more unstable (and slower). Another argument against is that we would have to change our jobs structure, cause in the docker container where the tests are performed we do not have access to full git repo.  
On the other hand this is what istio does on the post-submit jobs - https://github.com/istio/istio/wiki/Code-Coverage-FAQ#do-we-still-use-codecovio

## Summary
At this point we gather data about per-component test coverage and can preview it in [DataStudio](https://datastudio.google.com/s/mK56WnUz778).

## Next steps 
At this point we should define what kind of coverage metrics are really needed and how detailed they should be.

**Comment by adamwalach** [comment]
Coverage report is here: https://datastudio.google.com/s/kThiWcAfRMQ
