### ISSUE TITLE
kyma-vulnerabilites-scan: Snyk results are not updated

### ISSUE THREAD

**Issue by jose-cortina** [kyma-project/test-infra#1807]
**Description**

The kyma-vulnerabilities-scan triggers the Snyk scan for security (https://status.build.kyma-project.io/job-history/kyma-prow-logs/logs/kyma-vulnerabilites-scan)

The issues reported by Snyk have been the same for some time, and are not updated to the current state of the code.

As an example, Snyk https://app.snyk.io/org/kyma-project/project/f46632e8-e7e9-4b15-a5b3-8e3a8ebe3805/history/fb3e687b-3192-442c-a943-9f53da1bf11b reports a high issue for the event-bus component, stating that the Gopkg.lock contains a vulnerable library github.com/satori/go.uuid.

This library no longer appears in https://github.com/kyma-project/kyma/blob/master/components/event-bus/Gopkg.lock so this issue no longer exists.

**Expected result**

Reported vulnerabilities correspond to the latest status when they were scanned.

**Actual result**

Issues are outdated.

**Comment by Ressetkk** [comment]
@jose-cortina The Snyk reports have been updated only when vulnerabilities of high severity were found. The issue was due to command `snyk monitor` executing only when the vulnerability was found. The solution was to execute the above command during each component scan regardless of issues to update the report.

Fixed in #1901
