### ISSUE TITLE
Assure cleanup of network resources

### ISSUE THREAD

**Issue by mwieczorek** [kyma-project/test-infra#184]
Assure cleanup of network resources (f.e. LBs, IPs and related) after deleting of kyma cluster.

Right now when the kyma cluster is deleted some of network resources are left.
It should be also assured in periodic cleanup of leftovers described here #177

**Comment by Demonsthere** [comment]
Network resources that need to be purged:
- TargetPools
- HealthChecks
- IP Addresses
- DNS Entries
- ForwardingRules

**Comment by aszecowka** [comment]
This cleanup should be done:
- after finishing gke-integration-test
- periodically

**Comment by Demonsthere** [comment]
Splitting the task:
Cleaning of:
- TargetPools
- HealthChecks
- ForwardingRules
- InstanceGroups
- BackendServices
Has been already done in #220 

However, the cleanup of IpAddreses and DNSEntries requires more work on a different API, and will be addressed in a different ticket #275.
Because of that, this can be closed now.
