### ISSUE TITLE
Cleanup unused docker images

### ISSUE THREAD

**Issue by tehcyx** [kyma-project/test-infra#1853]
**Description**
There's quite a few images in parts of the registry that have weird paths and are never downloaded or leftovers from old tests. We can clean these, as they were never part of any release.

**Reasons**
Reduce clutter of containers on the repository.

**Comment by kasiakepka** [comment]
Daniel managed to prepare the [list of images](https://login.microsoftonline.com/42f7676c-f455-423c-82f6-dc2d99791af7/oauth2/authorize?client_id=00000003-0000-0ff1-ce00-000000000000&response_mode=form_post&protectedtoken=true&response_type=code%20id_token&resource=00000003-0000-0ff1-ce00-000000000000&scope=openid&nonce=EF172F2BB4F845269254D4D8065ABAC6CED9575DF43A1B4E-8CA63BCE5CCA0F6A847BD7C15FFF12376E66F38DD69108D27CF90A7CC09D7A0B&redirect_uri=https:%2F%2Fsapnam-my.sharepoint.com%2F_forms%2Fdefault.aspx&wsucxt=1&cobrandid=11bd8083-87e0-41b5-bb78-0bc43c8a8e8a&client-request-id=6b972d9f-f022-a000-c81e-54231e350d53).

**Comment by kasiakepka** [comment]
The first easy step will be to delete the images without tags.
[Images without tags.xlsx](https://github.com/kyma-project/test-infra/files/4102691/Images.without.tags.xlsx)

**Comment by adamwalach** [comment]
I noticed that some components (https://console.cloud.google.com/gcr/images/kyma-project/EU/application-broker?gcrImageListsize=30) have recent images without tags (1 mont old). It means that something is still pushing these images. We should first check what it is, so we don't have to clean it up once again.

**Comment by adamwalach** [comment]
These images are coming from commits to PRs. If a new commit is pushed the tag with PR name is set on the new image. The old one is left without any tag. So we will have the same problem in the future.

**Comment by kasiakepka** [comment]
Issues to overcome:
- We are missing clear guidelines on how to push images to the GCR, [community guidelines](https://github.com/kyma-project/community/blob/c397eb94c28fb8c71d1e580e402c3e4e0b592c62/guidelines/technical-guidelines/04-docker-images.md) are outdated and not incomplete.
- In order to have neatly and methodically arranged registry we need to start with fresh GCR. I believe that 90% of old images can't be deleted.
- All teams have to switch to new registry, Prow config also has to be adjusted.

Benefits:
- Neat and intuitively arranged registry so that it is easy to identify and maintain:
  a) component images
  b) all prow/test-infra images
  c) all release images
  d) PR images
  e) test/dummy images etc.
- Possibility to automate cleanup process

Current status:
We managed to clean up:
- `gcr.io/kyma-project/keventing-e2e-img/2823/*` and `gcr.io/kyma-project/keventing-e2e-img/21574/*`
- `gcr.io/kyma-project/null*`

**Comment by kasiakepka** [comment]
https://sap-cx.slack.com/archives/CCYFKUSQ7/p1580294574015900

**Comment by kasiakepka** [comment]
AC: 
- if all teams confirm that untagged images can be deleted - create Prow periodic to clean it up.

**Comment by kasiakepka** [comment]
It was confirmed with DEV teams that untagged images can be deleted from registry.

**Comment by adamwalach** [comment]
We can not proceed until we figure out a way to perform a backup.

**Comment by kasiakepka** [comment]
https://jira.multicloud.int.sap/plugins/servlet/desk/portal/2/MCO-114373

**Comment by kasiakepka** [comment]
Google of Multicloud team does not provide good solution to backup the registry hence we are dropping this task.
We are waiting for a possibility and good timing to create brand new repository. When it is possible we will introduce new policies when pushing to the registry and work on cleanup process.
