### ISSUE TITLE
Define naming schema for GCP resources

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#1945]
**Description**

***1. Service Accounts***
We should consider establishing policy for creation and naming of serviceaccounts in our projects.
We should define if we are going to use one serviceaccount for prod, test and dev instance for each purpose/user or we will create separate one for each environment.
In terms of naming, policy should give us ability to identify:
- if SA is a personal or nonpersonal one
- what application/automate or purpose it serves for
- which environment it belongs to.

***2. KMS***
Define policy of creating KMS for all the Neighbors project (kyma-prow, kyma-prow-workloads, sap-kyma-neighbors-dev)
- should we create separate KMS pee project
- do we need separate KMS for different/special purposes
- permissions/IAM

***3. Bucket***
Define Bucket naming conventions and organisation structure.
- how many buckets we have (do we need cleanup)
- how many buckets we need

**Reasons**

Establishing such policy is a foundation for future automation of sa management tasks.
It will allow faster SA identification.
It will give clear rules to follow for SA owners.

**Acceptance Criteria**

- All GCP resources are easy to identify and maintain
- All the agreements (regarding SA, buckets and KMs) are well described in documentation
- All necessary cleanup is completed (do not leave duplicates and old keys or service accounts)
- All existing serviceaccounts, KMS and buckets are migrated to follow established policy.
- Established rules were shared within Neighbors and Kyma organisation.

**Comment by kasiakepka** [comment]
**1. Service Accounts**
We can base our SA naming convention on:
`sa`- prefix for generic accounts 
`last_name`- last name prefix for private SAs (i.e. `kepka`)
`gcp-project`- one of GCP project shortcut like `workloads` for sap-kyma-prow-workloads, `dev` for sap-kyma-neighbors-dev, `prow` for sap-kyma-prow.
`application-name` - application name, purpose or tooll where this SA is used ie. gcs-plank, kyma-artifacts, gke-kyma-integration etc.

SAs names can start from the least specific information like environment and end on the very specific instance_id. Examples:
`sa-prow-gcs-plank-01`
`kepka-dev-01`
`sa-workloads-kyma-backup-restore-01`

_We can also add
gcloud iam service-accounts create test-to-remove \\n    --description "about" \\n    --display-name "displayname"_

**2. KMS**
In order to limit the scope of data accessible with any single key version each project should have one key ring per project.

| KEY RING         | KEY | PROJECT NAME           |
| ------------- |:-------------:|:-------------:|
| kyma-prow |  kyma-prow-encryption |sap-kyma-prow |
| prow-workloads | prow-workloads-encryption |sap-kyma-prow-workloads |
| neighbors-dev | neighbors-de-encryption |sap-kyma-neighbors-dev | 

Additional KEY parameters:
- type: symmetric key 
- location : `global` - it will be available in several global locations and across multi-regions
- rotation period: by default set to 90days

**Comment by kasiakepka** [comment]
Interesting solution developed by Google - https://forsetisecurity.org/

**Comment by dekiel** [comment]
What we consider as generic account, so where we should put sa prefix? I understand that "sa" prefix we use for non personal accounts.
In a last name prefix we should use first letter of first names, example: ppokrywka.
From examples I understand that we use number suffix to represent count of same accounts. I'm not sure if we should allow to have same accounts with different counter only. What might be the use case for more than one same account name.
We should add, optional prefix which can be five first letters of md5 from account name and creation time. This might be used in case we will have more than one instance of application using serviceaccounts on same project. This eventually remove need of having number suffix.
NPA service accounts should be limited to the project scope and/or environment(prod/test/dev) scope.
We should define that display name is everything before @ in account fqdn.
We should define that Description contains some details about what exactly sa is used for and it can't be equal to Display name or any part or whole sa fqdn. Like in an example.
We should define naming schema for buckets and KMS to follow rules for SA.

Feature of taking project snapshot looks interesting for our project stage. For other features we might not find time at present.

**Comment by kasiakepka** [comment]
`"What we consider as generic account, so where we should put sa prefix? I understand that "sa" prefix we use for non personal accounts."`
- I explained it a bit better in previous comment.

`"In a last name prefix we should use first letter of first names, example: ppokrywka."`
- Updated previous comment.

`"From examples I understand that we use number suffix to represent count of same accounts. I'm not sure if we should allow to have same accounts with different counter only. What might be the use case for more than one same account name."`
- This is an additional option that allows you to have separate SAs for different test/dev prow instance running on one GCP project. I don’t think it is necessary.

`" We should add, optional prefix which can be five first letters of md5 from account name and creation time. This might be used in case we will have more than one instance of application using serviceaccounts on same project. This eventually remove need of having number suffix."`

- I think that prefixes should be straightforward (easy to identify) - it is useful when you sort stuff. We can add md5 suffix. In IAM/Service Accounts you can find the information about creation date.

 `"NPA service accounts should be limited to the project scope and/or environment(prod/test/dev) scope."`
- Ok, so we should add additional prefix/suffix that will allow us to identify it.

  `"We should define that display name is everything before @ in account fqdn."`
- Display name does not appear before @, it is [SA-NAME] that appears before fqdn.

gcloud iam service-accounts create [SA-NAME]
--description "[SA-DESCRIPTION]"
--display-name "[SA-DISPLAY-NAME]" 

`" We should define that Description contains some details about what exactly sa is used for and it can't be equal to Display name or any part or whole sa fqdn. Like in an example."`
- Sure! The description can be quite long so we should be good. 
We should define naming schema for buckets and KMS to follow rules for SA.
- Keyring groups resources with related permission so we should decide how we will group them. I suggest to have one keyring per project and multiple keys splitter like SAs (one per environment).

**Comment by kasiakepka** [comment]
Document draft and primary version of the naming convention was described [here](https://github.com/kyma-project/test-infra/pull/2146). 
This document should be adjusted and updated along with the Prow-test setup.
