### ISSUE TITLE
Speed up test-infra tools execution

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#2154]
**Description**

All tools from https://github.com/kyma-project/test-infra/tree/master/development/tools/cmd download their dependencies and compile from source code on every execution. In the majority of our "cleaner" jobs most of the execution time is taken by dep.

**Acceptance Criteria**

* binary versions of our tools (we could have one master binary or multiple smaller ones) created on every commit to master
* cleaner jobs use the binary

Alternatively we could have a separate docker image with binaries inside - whatever is simpler to execute

**Attachments**

**Comment by Ressetkk** [comment]
There were some proposals on that:
* Compile the binaries to prebuilt packages and somehow deliver them to working pods.
* Cache just only the dependencies and still compile the files on the go.

The cleaners use one generic script called `resources-cleanup.sh` to compile and run the cleaners. For example let's pick *kyma-cli-integration-gke* job. The base script that is run defines a cleanup function. That function calls another helper script `delete-dns-record.sh` which calls `resources-cleanup.sh` with proper tool name. Similar pattern is used in different jobs that use the cleaner tools.

The idea was to completely omit the download dependencies and compile stage. We made a brainstorm on first case and came up with some ideas:
* Create separate image with binaries and attach them as a separate sidecar container.
* Add binaries to the base image so that are accessible by default.
* Add binaries to a persistent volume and attach this volume as a mount inside a test container.
* Mount GCP bucket in the runtime of a test container.

First option unfortunately is not an option, because Prow by design allows only one container to be defined in a spec. Otherwise `mkpj` will return an error. Using initContainers is also not allowed.

Second option would be the safest way because each contianer would have its own copy of the binaries. The cleaners use either `buildpack-golang` image, or use the image named `Kyma-cluster-infra` that uses `buildpack-golang` image as base. I think we can rebuild the `Kyma-cluster-infra` image without much hassle. That should make versioning a little bit easier. Or we can create new image based on a `Kyma-cluster-infra` with only binaries added.

Third and fourth options should be the fastest to implement in our environment.

The third one goes around bare Kubernetes by creating a new PVC that uses GCEPersistentDisk, however this mode only allows only two access modes: *ReadWriteOnce* - which only allows one node to use the drive in r/w, and *ReadOnlyMany* - which allows only read-only access by multiple nodes. That would make issues with updating the files in a ProwJob and changing the access mode in the runtime might make some unexpected issues.

Last option is the most ideal if we don't want to update the docker image. We can use the gcpfuse that is bundled with gcloud cli to mount the bucket and do some operations on it. We can also mount it in read-only mode.

I think the options one will be the most convenient and safe in terms of executing and updating.
Option four is also easy to do but it might make some problems with binaries versioning.

Of course both of the options will require changing the scripts from `go run` main file of each tool to call a prebuilt binary. It also shouldn't be a big deal since we can call binaries provided as an argument to `resources-cleanup.sh` script. The fourth option would require slightly more edits, because we will need to add mounting the bucket to a script, but it also can be done in `resources-cleanup.sh` script.

**Comment by Ressetkk** [comment]
In fact we can use `gsutil cp` to download and store a copy of a binary from a bucket that will be used. See #2171

**Comment by Ressetkk** [comment]
So I made two simple jobs. One post-submit job rebuilds binaries and uploads them on a bucket. http://status-dev.prow.build.kyma-project.io/view/gcs/upgrade-prow-logs/logs/post-master-kyma-cleaners-update-binaries/1243535885480235008

Second one is a periodic implementation of `orphaned-dns-cleaner` that uses resources-cleanup.sh that downloads desired binary and executes it. http://status-dev.prow.build.kyma-project.io/view/gcs/upgrade-prow-logs/logs/orphaned-dns-cleaner-prebuilt-bucket/1243545572342763520
Those job execution times look very promising and it looks like it would only need to edit `resources-cleanup.sh` script and add a preset that defines GCS bucket with cleaner binaries.

However building separate image with the tools and use this image in jobs should be overall much cleaner and more reliable when working on more than one prow instance - as we are having test and live prow instance for now.
