### ISSUE TITLE
Enable option to dismiss approved reviews after a new commit

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#2327]
**Description**

Currently, after we get all required approvals on a PR we can change whatever we want and the PR can be merged without any additional reviews. 
We should enable the `dismiss_stale_reviews` option to dismiss approved reviews automatically when a new commit is pushed -
https://github.com/kyma-project/test-infra/blob/6cac6abb8e8efa242c4a69f47cc1f55947540d34/prow/config.yaml#L506

**Reasons**

Setting it this way will increase security - it could mitigate an issue when is someone changing the PR in last minute with some secret exposure.

**Acceptance Criteria**

All existing approvals are removed after a new commit is pushed.
We could set it up on smaller repos first (test-infra, cli, octopus) and after few weeks when everyone are used to it enable it on kyma repo.

**Attachments**

**Comment by adamwalach** [comment]
`test-infra`, `cli` and `rafter` repos are set

**Comment by kazydek** [comment]
I just wanted to point out that PRs in which you modify both code and docs will not be that straightforward as that's usually a two-stage process - once you get approval from a fellow dev and ask TWs for the docs review, you will need to ask the devs for re-approving the PR every time TW approves it (assuming there are changes in docs to be made). I hope that's ok for everyone as well.

**Comment by pkosiec** [comment]
Hi,

I think enabling this option by default can increase time in development, especially the cross-component stuff. 

**Example**
Let's say we want to modify one component (like Rafter), which involve code changes + documentation.

Previously our workflow looked more or less like this:
1. implement code change + create documentation
1. review from devs (code + docs content)
   - fixes for dev review
   - approve from devs
1. Technical Writers review
   - fixes from TW review
   - approve from TW
1. merge

Now, we would need to require another round of approval from devs after TW review. When the change is bigger, cross-component, it involves double approvals from multiple code owners.

IMHO this is inconvenient. I wonder how many percentage of the second approvals will be blind ones, which means clicking "Approve" without looking at the code. (Yup, GitHub brought new feature showing changes which appeared "since last review", but it doesn't work when force pushing e.g. after rebase).

>  it could mitigate an issue when is someone changing the PR in last minute with some secret exposure.

@adamwalach Were there any incidents like this in the past? 
GitHub has [secret scanning](https://help.github.com/en/github/administering-a-repository/about-secret-scanning) for popular service providers, so at least it would block e.g. GCP, GitHub or NPM credentials.

**Comment by adamwalach** [comment]
The main idea is to protect the code that we have in the master branch. When you are able to commit any changes without someone else looking at the PR it means that you could override the build scripts (Makefiles) for the docker images and potentially override something that is used in a previous release.
Possible solutions:
- creating 2 PRs, one for docs and one for code
- we will re-tag all images during release process to use completely different docker registry that is protected and can be used only from a release job - that's not an easy task (we still don't have list of all images used by a given release, all charts need to be changed)

One more thing - we plan to implement tide (https://github.com/kyma-project/test-infra/issues/1079) - from what I understand it was desired by many dev teams. Assuming that we will be able to fix issue mentioned by @mmitoraj about `.md` files, then the process with approvals and merging may be even more strict.

**Comment by tehcyx** [comment]
In my opinion it is a good approach to have this enabled not only for the reasons @adamwalach already mentioned but also to streamline the review process better. The issue right now being, that approvals are blanket approvals where they shouldn't be.
If I approve a PR the author can change literally anything he wants on the PR and merge it after without anyone ever looking over it again. This is a big issue. Therefor for me the only solution I see is to enable stale reviews, so that we get more control over what is merged.

**Comment by mszostok** [comment]
_my two cents_
If we're really thinking about switching to `tide` then I'm ok with that change as we can play more around it and get used to it. 

But if `tide` is just a thing of far future then in the current situation I totally agree with @pkosiec:
> IMHO this is inconvenient. I wonder how many percentage of the second approvals will be blind ones, which means clicking "Approve" without looking at the code.

tide gives you the ability to remove the `write` perm from org members which contribute to our repos (now it's necessary so e.g. anyone can push branches to upstream 😞 ). It's also good for big projects and if you have external contributors (which is not the case for us as we don't have them right now)

about comments like:
> If I approve a PR the author can change literally anything he wants on the PR and merge it after without anyone ever looking over it again

I cannot agree with them. I give approval when everything is fine or I leave a few comments which are *nit*. We all in the same org and I trust people who receive my approval. Remember that even reviewer is not infallible and as Paweł said probably such run of next review will only end up with blind approvals, so such thing IMO will not increase the security but only reduce time to merge. 

IMO the best solution is to enable `dismiss_stale_reviews` only for external contributors who we cannot trust but AFAIK this is not possible 😞

**Comment by suleymanakbas91** [comment]
I totally agree with @pkosiec and @mszostok. In addition to their points, I think people will also start avoiding making improvements on the cross-component PRs because they wouldn't want to get another set of approvals just to do some small improvements. This will lower the quality of the code and harm us more in the end. 

> IMO the best solution is to enable dismiss_stale_reviews only for external contributors who we cannot trust but AFAIK this is not possible

Can't we only allow the people from the organization to merge the PRs? So that even if external contributors make a change after receiving all the approvals, they won't be able to merge the PR anyway.

**Comment by pkosiec** [comment]
> Can't we only allow the people from the organization to merge the PRs?

I think that's the case right now. Organization members have write access, external people doesn't. There are also ["Outside collaborators"](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/adding-outside-collaborators-to-repositories-in-your-organization and the access rights for them are configurable.

**Comment by sjanota** [comment]
OK, first example against having this option enabled in Kyma repo: https://github.com/kyma-project/kyma/pull/8572.

I already spent a whole day catching people for review, then when I needed to resolve conflict irrelevant for most of them (image version) I needed to hunt them again.

**Comment by pkosiec** [comment]
Example: PR where we synchronized whole Compass chart, so multiple codeowners were involved and they needed to approve the PRs multiple times, even when the corresponding subcharts weren't modified since last review: https://github.com/kyma-incubator/compass/pull/1405

**Comment by majakurcius** [comment]
Question: would it be possible to enable this option but with a twist so that, if changes are made after a codeowner has approved the PR, only the review of the codowner(s) of the changed file is dismissed? That would ensure that only the interested party needs to have another look and re-approve it and would, for sure, speed up development while maintaining the security that we're after.

*Example 1*: there's a PR slightly altering a certain functionality in a given component and modifying a line in its documentation. A dev-codeowner approves the changes in code, then it goes through a TW's review, the TW-codeowner approves it, but then the author remembers that they forgot to add one more line in the documentation and add one more commit, and now, as it's just the `.md` file that's been changed since the approvals, only the TW's approval is dismissed. 

*Example 2*: there's a PR slightly altering a certain functionality in a given component and modifying a line in its documentation. A dev-codeowner approves the changes in code, then it goes through a TW's review, the TW requests some changes which the author introduces, but since they're made only to the `.md` files whose codeowners are TWs, the dev's approval stays in place and is still valid. 

Would that be possible?

**Comment by kasiakepka** [comment]
[Slack thread about the topic ](https://sap-ti.slack.com/archives/C0140PCSJ5Q/p1591625919186300)

**Comment by Wawrzyn321** [comment]
And another example https://github.com/kyma-project/console/pull/1841. @majakurcius's idea sounds like a sane compromise, but we would be still pestered by merges.

**Comment by pbochynski** [comment]
We had it enabled for 1 release and only 2 cases were reported. In comparison to the number of all PRs it is not a big impact.
