### ISSUE TITLE
Create new GCE image with Minikube v1.12.2

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#2671]
**Description**

We need to merge this PR (https://github.com/kyma-project/test-infra/pull/2578/files) and then create a custom image following this doc https://github.com/kyma-project/test-infra/tree/master/development/custom-image

**Reasons**

**Acceptance Criteria**

**Attachments**

**Comment by Ressetkk** [comment]
The new image has been created and everything seems to be working, but there is a but in the installation script. The problem is in this line https://github.com/kyma-project/kyma/blob/95e3dfe71d805c09fcf2e9327762d9345188e6c6/installation/scripts/minikube.sh#L113
It seems that the minikube changed the way it shows the results.

The command `minikube status --format "{{ .Host }}"` under version 1.12.2 returns the following message:
```
🤷  There is no local cluster named "minikube"
👉  To fix this, run: "minikube start"
```
However under minikube version 1.6.2 it returns nothing. This forces the script to fail prematurely and fail the prowjob.

**Comment by a-thaler** [comment]
We really should migrate to the Kyma CLI here.. it is fixed there already

**Comment by Ressetkk** [comment]
That would require the rewrite of https://github.com/kyma-project/kyma/blob/master/installation/scripts/prow/kyma-integration-on-debian/deploy-and-test-kyma.sh to use the Kyma CLI.

Also after checking the affected jobs the following jobs will be at least affected:
- pre-master-kyma-integration
- post-master-kyma-integration
- pre-rel115-kyma-integration
- pre-rel114-kyma-integration
- pre-rel113-kyma-integration

**Comment by Ressetkk** [comment]
The pipeline has been rewritten to use Kyma CLI and is using new minikube v1.12.2. Successful test run: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/9400/pre-master-kyma-integration/1304051916900143104

**Comment by Ressetkk** [comment]
The changes had to be reverted. #2766
