### ISSUE TITLE
Run Prow Jobs on a separate cluster than Prow components

### ISSUE THREAD

**Issue by strekm** [kyma-project/test-infra#27]

**Comment by Demonsthere** [comment]
Hi,
I would suggest to consider using an external management tool to provision clusters rather than doing it using raw gcloud commands. This would allow for cloud independence. 
Good options to look into would be [Gardener](https://github.com/gardener/gardener) and [Kubespray](https://github.com/kubernetes-incubator/kubespray)

**Comment by suleymanakbas91** [comment]
See [this](https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md#run-test-pods-in-different-clusters)

**Comment by abbi-gaurav** [comment]
Taken #403. So removing this from the Malones backlog.

**Comment by crabtree** [comment]
Make sure that only required secrets will be populated to each cluster.

**Comment by sayanh** [comment]
@Demonsthere I see there is no point in managing k8s clusters ourselves. This was never the goal of Kyma team. IMO going with gcloud commands is totally fine here. Benefit of cloud independence is not a real advantage as this solution is not meant for customers where there is a possibility of using different cloud providers. I mean we could do it definitely but IMO this is not worth it at this moment.
