### ISSUE TITLE
Stale reports in testgrid

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/test-infra#2900]
**Description**

Reports for some of our jobs are [not updated](https://testgrid.k8s.io/kyma_integration#post-master-kyma-gke-upgrade):
<img width="1440" alt="Screenshot 2020-10-28 at 12 19 29" src="https://user-images.githubusercontent.com/8530211/97429508-d0071780-1917-11eb-81d3-dbdb1d735a1e.png">
 

**Expected result**

Reports should contain all available results (in the example above it should be up to 28.10) 

**Steps to reproduce**

We noticed this problem several times in multiple job types. I suspect some of our XMLs are broken and if they are in the scope of a given report it breaks rendering.

**Troubleshooting**

The first column shows partial results for the following job:
https://console.cloud.google.com/storage/browser/_details/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1305232703074865152/artifacts/junit_Kyma_octopus-test-suite.xml

This xml looks like it's damaged:
<img width="583" alt="Screenshot 2020-10-28 at 12 22 14" src="https://user-images.githubusercontent.com/8530211/97429787-312eeb00-1918-11eb-9939-919d07d01600.png">

**Comment by adamwalach** [comment]
Possibly relevant: https://github.com/kyma-project/cli/pull/612

**Comment by tehcyx** [comment]
Fix did not actually work, as I found an error for in a run on Oct 26th: https://console.cloud.google.com/storage/browser/_details/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1320681248284217344/artifacts/junit_Kyma_octopus-test-suite-1603712281.xml

Downloading and opening that file in VSCode the errorneous line seems to be one with shell color coding, but the position of the error (if accurate) would make me guess it is an invisible character problem.

**Comment by tehcyx** [comment]
Doing some more digging, especially on the file I found. The error seems to possibly be related to the progress bar creation of the npm tool `cypress`. In this screenshot <img width="1279" alt="image" src="https://user-images.githubusercontent.com/917785/97619284-43bf2800-19dd-11eb-8330-c3f7e5799d48.png"> I have not highlighted a single character but placed the cursor into the line and get highlights of other characters throughout the `cypress` output. Assuming, that this is an invisible character I'd propose to disable the progress bar output if possible. Also maybe transforming this to junit output to be put into the artifact folder via
```
cypress run --reporter junit --reporter-options mochaFile=artifacts/cypress-run.xml,toConsole=true
```
With the additional required paramters that we already have for the tool, with the option to eventually turn this `toConsole` parameter to false.

**Comment by Ressetkk** [comment]
So, I have resolved the problem. It was indeed issue with malformed JUnit report XML file. The "solution" was to remove all the malformed XMLs since 22-9-2020 from the artifacts of each stalled job.
The jobs that got stalled are:
* post-master-kyma-gke-integration since 23-9-2020
* post-master-kyma-gke-central-connector since 23-9-2020
* post master-kyma-gke-upgrade since 13-9-2020

I suspect that console specific bytes of VT100 terminal, which were somehow incorrectly parsed to utf8, garbled the XML.

Screenshots:
![image](https://user-images.githubusercontent.com/23667947/99088294-2b016580-25cc-11eb-8cae-470be149067a.png)
![image](https://user-images.githubusercontent.com/23667947/99088328-33f23700-25cc-11eb-93d0-c63deeb28ff5.png)
![image](https://user-images.githubusercontent.com/23667947/99088360-3bb1db80-25cc-11eb-9159-bd00a87f5bf7.png)

**Comment by Ressetkk** [comment]
The problem still persists. https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-integration/1328263533271453697

https://storage.googleapis.com/kyma-prow-logs/logs/post-master-kyma-gke-integration/1328263533271453697/artifacts/junit_Kyma_octopus-test-suite-1605518975.xml

**Comment by tehcyx** [comment]
Looks a lot like the same thing, maybe another (different) invisible character or the `toConsole` parameter is not doing what it promises.

**Comment by Ressetkk** [comment]
There are still garbage escape characters from cypress report. I see that changing the report to JUnit output would also not change much, Cypress generates different test suite for each test run. https://docs.cypress.io/guides/tooling/reporters.html#Custom-reporter section `Multiple reporters` I think the output should be stripped from garbage characters while generating the JUnit report. I also think we should avoid generating the JUnit report in Cypress because we'd end up with multiple CDATA fields that cannot be nested.
![image](https://user-images.githubusercontent.com/23667947/99379469-00aff080-28c9-11eb-98a1-5ce1f11d51d4.png)
![image](https://user-images.githubusercontent.com/23667947/99381982-1ecb2000-28cc-11eb-9712-b29a2ecf59f0.png)

**Comment by Ressetkk** [comment]
The problem might be that we take the console output from each pod as-is without caring about what's in. I speculate that this is something which should be handled by the kyma-project/cli fetcher.go. https://github.com/kyma-project/cli/blob/4dc8853bc71efb4f78e63519d77c8a559873bc65/internal/logs/fetcher.go#L64

The raw body is a byte slice which contains invalid characters.
