### ISSUE TITLE
Tidy up the prow/scripts directory

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#2974]
**Description**
At this point the `prow/scripts` directory contains a lot of unnecessary scripts and duplicated code. We should take some time on planning the rewrite and tidying up the scripts that are in that directory. 

**Reasons**
As for now the directory is hard to maintain because a lot of scripts use duplicated code. Scripts contain mostly copied functions from libraries, instead of sourcing them. This creates unwanted complexity and increases the time of editing the scripts. 

**Acceptance Criteria**
* Remove unused scripts from the directory
* Reduce the complexity of the scripts by moving shared code to the `lib/` directory as separate scripts
* Rearrange the directory structure for better maintainability
* Create proper README.md files with info about the directories
* Completely remove deprecated `library.sh` script
* Ensure `set -u` is added in the scripts to fail when variable is not set

**Attachments**

**Comment by Halamix2** [comment]
`library.sh` entires are intentionally omitted, as it is deprecated

## `runTestLogCollector`
```bash
grep -Rni "runTestLogCollector()" *  
cluster-integration/kyma-upgrade-gardener-azure.sh:131:runTestLogCollector(){
cluster-integration/kyma-gke-rel2rel-upgrade.sh:80:runTestLogCollector() {
cluster-integration/kyma-integration-gardener-gcp.sh:127:runTestLogCollector(){
cluster-integration/kyma-integration-gardener-azure.sh:472:runTestLogCollector(){
```
* only `PROW_JOB_NAME` differs
* `cluster-integration/kyma-gke-rel2rel-upgrade.sh` is slightly outdated
  * uses `enableTestLogCollector` instead of `ENABLE_TEST_LOG_COLLECTOR`
  * `if [[ "$BUILD_TYPE" == "master" ]]; then` is missing `|| [[ -z "$BUILD_TYPE" ]]` condition

## `testSummary`
```bash
grep -Rni "testSummary" *     
cluster-integration/kyma-integration-gardener-aws.sh:66:        testSummary
cluster-integration/kyma-integration-gardener-aws.sh:95:testSummary() {
cluster-integration/kyma-upgrade-gardener-azure.sh:100:        testSummary
cluster-integration/kyma-integration-gardener-gcp.sh:71:        testSummary
cluster-integration/kyma-integration-gardener-gcp.sh:100:testSummary() {
cluster-integration/kyma-integration-gardener-azure.sh:138:        testSummary
cluster-integration/kyma-integration-gardener-azure.sh:177:testSummary() {
```
* `cluster-integration/kyma-upgrade-gardener-azure.sh:100 testSummary` - calls nonexistant function
* Azure one uses `log` lib
* AWS/GCP additionally calls `kubectl get cts "${SUITE_NAME}" -oyaml` on fail

## `cleanup()`
```bash
grep -Rn "cleanup()" cluster-integration/kyma-integration-gardener*.sh
cluster-integration/kyma-integration-gardener-aws.sh:59:cleanup() {
cluster-integration/kyma-integration-gardener-azure.sh:117:cleanup() {
cluster-integration/kyma-integration-gardener-gcp.sh:61:cleanup() {
```
* `cluster-integration/kyma-integration-gardener-gcp.sh`, `gcp` and `kyma-upgrade-gardener-azure.sh` are the same (`upgrade` uses log isntaead of shout),
* `cluster-integration/kyma-integration-gardener-azure.sh ` is different
  * it has "`describe nodes`" section
  * it has check if `testSummary` fails
  * deletes "`Azure EventHubs Namespace`"
  * calls "`"${TEST_INFRA_CLUSTER_INTEGRATION_SCRIPTS}/delete-image.sh"`"
* `cluster-integration/kyma-upgrade-gardener-azure.sh` is slightly newer

---
# `kyma-integration-gardener-*.sh`
These functions below may exist only in one of the `kyma-integration-gardener-*.sh` file, but the rest of them have similar structure in place, waiting for refactorization

## `provision_cluster`

* might be hard to consolidate
* Azure has different scaler numbers
* Azure has `disk-type` argument

## `install_kyma`

* Exists in `cluster-integration/kyma-integration-gardener-azure.sh`
* `cluster-integration/kyma-upgrade-gardener-gcp.sh` creates static config file for parallel every time, even if parallel instalation was not selected
* each provider (Azure, GCP, AWS) have different command here, this is the most unique part of `kyma-integration-gardener*` scripts


## `test_kyma`
* Exists in `cluster-integration/kyma-integration-gardener-azure.sh`, could be exported as-is*
* azure and gcp have different timeout (120m and 90m)

## `hibernate_kyma`, `wake_up_kyma`, `pods_running`, `check_pods_in_namespaces`, `wait_for_pods_in_namespaces`, `test_local_kyma`, `test_fast_integration_kyma`

* only defined in `cluster-integration/kyma-integration-gardener-azure.sh`
* all of them seem to be good to export to different file as-is
* `hibernate_kyma` has typo in `echo "Hibenration for this cluster is not possible! Please take a look at the constraints :"`

# misc

* Nothing seems to be using `cluster-integration/helpers/cleanup-gardener.sh` (`grep -Rn "cleanup-gardener" *`)

**Comment by Halamix2** [comment]
## `kyma-gke-minio-gateway-migration.sh`, `kyma-gke-minio-gateway.sh`
* first ~300 lines have only 9 differences
* `grep -Rni "kyma-gke-minio-gateway" ~/test-infra` is empty

## check if vars are set
* Multiple scripts (13) have similar structure at the beginning:
```bash
for var in REPO_OWNER REPO_NAME DOCKER_PUSH_REPOSITORY KYMA_PROJECT_DIR CLOUDSDK_CORE_PROJECT CLOUDSDK_COMPUTE_REGION CLOUDSDK_COMPUTE_ZONE CLOUDSDK_DNS_ZONE_NAME GOOGLE_APPLICATION_CREDENTIALS GARDENER_KYMA_PROW_PROJECT_NAME GARDENER_KYMA_PROW_KUBECONFIG GARDENER_KYMA_PROW_PROVIDER_SECRET_NAME; do
  if [ -z "${!var}" ] ; then
    echo "ERROR: $var is not set"
    discoverUnsetVar=true
  fi
done
if [ "${discoverUnsetVar}" = true ] ; then
  exit 1
fi
```
* A function could be created, that expects a list of required vars as argument

### list of files
```bash
grep -Rnil "for var in REPO_OWNER" ~/test-infra/prow/scripts/cluster-integration
compass-gke-integration.sh
control-plane-gke-integration.sh
kyma-gke-central.sh
kyma-gke-compass-integration.sh
kyma-gke-external-registry.sh
kyma-gke-integration-xip.sh
kyma-gke-integration.sh
kyma-gke-minio-gateway-migration.sh
kyma-gke-minio-gateway.sh
kyma-gke-rel2rel-upgrade.sh
kyma-gke-release-candidate.sh
kyma-gke-upgrade-xip.sh
kyma-gke-upgrade.sh
```

# `compass-gke-integration.sh`, `control-plane-gke-integration.sh`, and `kyma-gke-compass-integration.sh` have many similar functions

## `createCluster()`
```bash
grep -Rni "createCluster()" *                                               
compass-gke-integration.sh:75:function createCluster() {
control-plane-gke-integration.sh:85:function createCluster() {
helpers/create-cluster.sh:14:function createCluster() {
kyma-gke-compass-integration.sh:92:function createCluster() {
kyma-gke-long-lasting.sh:78:function createCluster() {
kyma-gke-rel2rel-upgrade.sh:212:createCluster() {
kyma-gke-upgrade-xip.sh:160:function createCluster() {
kyma-gke-upgrade.sh:193:function createCluster() {
```
* `compass-gke-integration`, `control-plane-gke-integration`, and `kyma-gke-compass-integration` have the same function definition
* `kyma-gke-rel2rel-upgrade`, `kyma-gke-upgrade-xip`, and `kyma-gke-upgrade` have the same function definition
  * `kyma-gke-upgrade` uses `log` lib
* there is unused `helpers/create-cluster.sh` similar to these functions

## `applyKymaOverrides`
```bash
grep -Rni "applyKymaOverrides()" *
compass-gke-integration.sh:122:function applyKymaOverrides() {
control-plane-gke-integration.sh:132:function applyKymaOverrides() {
kyma-gke-compass-integration.sh:139:function applyKymaOverrides() {
```
* this function could be split into two functions (common part in the first one and `dex-overrides`/`ory-overrides` in another)
  * `istio-overrides` are sligthly different
    * `compass-gke-integration.sh` and `kyma-gke-compass-integration.sh` ahsre the same configuration based on creation of a new file
    * `control-plane-gke-integration.sh`  passes gateway IP as `--data` argument
  * `compass-gke-integration.sh` and `control-plane-gke-integration.sh` additionally contains `dex-overrides`, and `ory-overrides`

## `applyCompassOverrides`
```bash
grep -Rni "applyCompassOverrides()" *
compass-gke-integration.sh:178:function applyCompassOverrides() {
control-plane-gke-integration.sh:177:function applyCompassOverrides() {
kyma-gke-compass-integration.sh:185:function applyCompassOverrides() {
```
* common `compass-auditlog-mock-tests` part
* `compass-gke-integration.sh` and `kyma-gke-compass-integration.sh` have common `provisioner-tests-overrides` part
* `compass-gateway-overrides` exists only in `kyma-gke-compass-integration.sh`

## unused scripts in cluster-integration
```bash
cd ~/test-infra/prow/scripts/cluster-integration
for f in *.sh; do; t=`grep -Rni $f ~/test-infra`; if [[ -z $t ]]; then; echo $f; fi; done

kyma-gke-integration-xip.sh
kyma-gke-minio-gateway-migration.sh
kyma-gke-minio-gateway.sh
kyma-gke-upgrade-xip.sh
```

## unused scripts in cluster-integration/helpers
```bash
cd ~/test-infra/prow/scripts/cluster-integration/helpers
for f in *.sh; do; t=`grep -Rni $f ~/go/src/github.com/kyma-project/test-infra`; if [[ -z $t ]]; then; echo $f; fi; done
create-cluster.sh
delete-dns-record-gcloud.sh
delete-network-with-subnet.sh
get-helm-certs.sh
```

## `kyma-integration-k3s.sh` script
* calls nonexistent scripts, probably broken

**Comment by Halamix2** [comment]
`set -u` there was a discussion if it should be added
Pros:

* errors on unset variables

Cons:

* if the variable is optional (`if [[ -n "${VAR}" ]]`) it has to have default empty value to not fail (`if [[ -n "${VAR:-}" ]]`), all if's with `[[ -z ]]` and `[[ -n ]]` would have to be edited
