### ISSUE TITLE
Create gardener based long running clusters for fast integration execution

### ISSUE THREAD

**Issue by k15r** [kyma-project/test-infra#4127]
**Description**

Create a long running gardener cluster (nightly/weekly) and execute fast-integration on it

**Acceptance**
- [x] new job for setup of long running gardener based cluster
- [ ] adapt kyma-gke-nightly-fast-integration to use the new clusters

**Comment by Ressetkk** [comment]
As for now there are two jobs - one is working, and the second is in the works:
* [skr-azure-nightly](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/skr-azure-nightly/1462950293535723520) - removes previously deprovisioned SKR, provisions a new instance, registers it to the compass scenario and runs set of OIDC and CommerceMock tests.
* [skr-azure-test-nightly](https://github.com/kyma-project/test-infra/pull/4385) (draft) - runs CommerceMock tests on the existing cluster for hourly basis.

As for now there are issues with running CommerceMock tests on newly provisioned cluster due to the ServiceInstances mutating webhook timing out on requests. More information are provided in https://github.com/kyma-project/kyma/issues/12673.

**Comment by Ressetkk** [comment]
I believe there is no real need to push this topic further since the priority is low. If the topic is still open please reopen this issue.
