### ISSUE TITLE
Problems related to Spyglass

### ISSUE THREAD

**Issue by pkosiec** [kyma-project/test-infra#450]
**Description**

There are two bugs related to Spyglass:
1. The logs are not visible in Spyglass until job completion
1. The spyglass icon hides once the job is completed. You need to click on the Job title to see the details.

**Expected result**

Just like on https://prow.k8s.io:

1. Spyglass icon is always visible
1. Spyglass does always show logs, even if build is in progress

**Steps to reproduce**

1. Run a job
1. Click on Spyglass icon. Bug no. 1: logs are missing
1. Wait for job completion. Bug no. 2: The spyglass icon is not visible anymore

**Comment by suleymanakbas91** [comment]
Configuration is fine. Both problems appear because we don't use gubernator. There is already a migration plan from gubernator to spyglass in prow. Once they completely move to spyglass, these problems will go away. You can find a discussion about this problem [here](https://kubernetes.slack.com/archives/CDECRSC5U/p1545257407349800).

**Comment by suleymanakbas91** [comment]
This one is addressed when we upgraded the Prow cluster: #590
