### ISSUE TITLE
Kyma-integration VM - investigate preemptible VMs

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/test-infra#48]
This is follow up task for https://github.com/kyma-project/test-infra/pull/44

Currently, we create regular VM for running integration tests. We should investigate if we can use preemptible VM (https://cloud.google.com/compute/docs/instances/preemptible).

I compared Preemptive vs Regular VMs (10h a day, 5 days in a week, 1 instance) and for one month we have the following  costs respectively: 51$ and 10.69$

**Comment by suleymanakbas91** [comment]
TODO: Calculate how much we'll save if we use preemptible resources to decide if it is worth the hassle.

**Comment by AHabes** [comment]
After a quick investigation on Preemptible VMs, few points to note:

1. For (10 hours per day, 5 days per week, 20 GB persistent disk, 1 instance), the monthly cost is 44.88$ for Regular VM vs 10.46$ for Preemptible VM

2. Preemptible instances are finite Compute Engine resources, so they might not always be available.

3. Compute Engine might terminate preemptible instances at any time due to system events.

4. Average preemption rate varies between 5% and 15% per day per project, and occasionally spiking higher depending on time and zone.

5. Compute Engine always terminates preemptible instances after they run for 24 hours. Certain actions will reset this 24 hour counter (actions like start & stop the instance).

6. Preemptible VMs are not covered by any Service Level Agreement.

**Comment by kasiakepka** [comment]
Before we implement this feature, it is necessary to identify if VM was killed by GCP or it failed due to performance/other reasons.

**Comment by adamwalach** [comment]
All our clusters are scaled dynamically based on the load. Introducing pre-emptible VMs may introduce additional instability in our test environments that may bring a lot of issues compared to the amount of money we can save.
