### ISSUE TITLE
Provide easy access to job logs from PR view

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/test-infra#57]
**Description**
AC: As a Kyma developer, I am able to see an output from the test, by clicking on `Details` link for given check

To achieve that, we need to:
- make `prow-production` bucket publicly viewable
- pass `--spyglass` flag to Deck
- add Spyglass configurations to `config.yaml` as a part of Deck configurations
- define `job_url_template` on Plank configuration

**Comment by suleymanakbas91** [comment]
We can't use Spyglass link in GitHub yet. That's why we need to setup Gubernator as well. So, we'll be using Spyglass to see the job details on Deck and Gubernator to reach the job details from GitHub. 

Currently, there is a problem with the usage of `/` in our job names. I asked [this](https://kubernetes.slack.com/archives/CDECRSC5U/p1542798595238300) on Prow Slack channel. Let's see what we can do after getting an answer.

**Comment by suleymanakbas91** [comment]
Thanks to [this recent PR](https://github.com/kubernetes/test-infra/pull/10228), we don't need to deploy anything else but Spyglass. To use it, we need to update our prow instance to a newer version including this PR.
