### ISSUE TITLE
POC: Integrate Jenkins with GCP secret manager

### ISSUE THREAD

**Issue by Halamix2** [kyma-project/test-infra#5832]
**Description**

Jenkins use secret manager API to get secrets.

- [x] create tool that updates Jenkins secrets from GCP Secret Manager
- ~~[ ] Clean up old versions of secrets after rotation~~ Not in scope of POC.
    - ~~[ ] send notification about secret rotation to pubsub~~ Not in scope of POC.
    - ~~[ ] Create cloud function cleaner that intercepts the pubsub message~~ Not in scope of POC.

**Reasons**

**Acceptance Criteria**

- [x] Service accounts used by Jenkins are rotated
- [x] Old keys are cleaned up after they are no longer used by Jenkins
- ~~[ ] Logs are stored in GCP~~ Not in scope of POC.
- ~~[ ] Notifications on failures are sent on Slack~~ Not in scope of POC.

**Attachments**

- Epic: #5691

**Comment by dekiel** [comment]
@Halamix2 can we use some plugin to get secrets from secret manager to our Jenkins? Example: https://plugins.jenkins.io/gcp-secrets-manager-credentials-provider/

**Comment by dekiel** [comment]
Credentials API plugin provide a way to update secrets in Jenkins secrets store over REST API https://github.com/jenkinsci/credentials-plugin/blob/master/docs/user.adoc#managing-an-existing-credentials-instance and using Jenkins CLI. https://github.com/jenkinsci/credentials-plugin/blob/master/docs/user.adoc#updating-credentials

**Comment by dekiel** [comment]
Did a research on possible implementation. A GCP Secret Manager plugin looks promising. It provides a GCP backed crendetials store in Jenkins. All pipelines using credentials from this store query a Secret Manager for secret value at the time of usage. This means there is no need to update secrets values on Jenkins. Once a new version of secret is added in Secret Manager it will be used by Jenkins.

However I'm facing issue with setting up this plugin. I've asked for help on a jaas slack channel.
Details about problems in setting it up.
> I’ve installed plugin and provided GCP project id in plugin config. Did add required permissions on GCP for dedicated service account. The tricky part is how to provide service account json file with credentials. The plugin uses an env variable GOOGLE_APPLICATION_CREDENTIALS which should hold path to the json file. I can use an uploadFile project to upload json file to $JENKINS_HOME/uploadedContent/ but how to setup a env var? I’ve created an environment variable under Node Properties in configuration of Built-In Node, but when checking it’s value through Script Console println System.getenv("GOOGLE_APPLICATION_CREDENTIALS") I’m getting null value. A Jenkins logs contains.
Oct 13, 2022 9:55:54 AM WARNING io.jenkins.plugins.credentials.gcp.secretsmanager.CredentialsSupplier get
Could not retrieve the credentials from GCP Secrets Manager
io.grpc.StatusRuntimeException: PERMISSION_DENIED: Request had insufficient authentication scopes.
GCP Secret Manager plugin docs: https://plugins.jenkins.io/gcp-secrets-manager-credentials-provider/

 Assuming it will be possible to use GCP Secret Manager plugin we will need another solution to update a credentials used by the plugin itself. For this purpose I've created a flow chart representing major steps and components.
 
A flow reuse existing cloud functions for rotating GCP service accounts keys.
A flow use a google workflow for part of updating secret value on endpoints. A GCP workflow can run part of workflow based on condition check. This can be used to run required update channel. An update channel is a way how the secret value update is done. For this case and updated channel would be to push commit to github. Another update channel can be added later as needed. Decision about which channel to use, is made based on Secret Manager secret annotations.
 
![jenkins_secret_update](https://user-images.githubusercontent.com/12400578/195586003-2f112981-19b7-4382-b2c7-77a21b4cf27d.jpg)

If usage of GCP Secret Manager plugin wont be possible all secret can be updated using above flow.

Many secrets we store for Jenkins holds configuration for tools running in pipelines. As a next step we should extract configuration part from secrets and store them as config files in github. This files would be downloaded from github on each pipeline execution. Such separation is more natural and give us a way to have multiple pipelines running same code with different configuration using the same credentials/secrets for interacting with external services.

We need to research if it's possible to automatically rotate secrets in a services for which we have secrets in Secret Manager. At present these are github instances and security scanners.

A security-scans-pipelines Dockerfile should be removed. We don't use this image anymore.

**Comment by dekiel** [comment]
POC is ready with following flow.
1. A secret for test service account is set to rotate every 3 hours.
2. Secret-manager send pubsub message when rotation is needed. This messages are consumed by existing cloud function which creates a new key for sa and add it as a new version in secret manager.
3. Secret-manager send pubsub message when new secret version is added.
4. Message is send to github update channel cloud run through a subscription with messages filtering enabled. Only messages with attribute `eventType` set to `SECRET_VERSION_ADD`.
5. Github update channel cloud run commit to tools github a secret update event file with new version number. A file is located commited to `secrets-sync` branch and is located under path representing secret path in Google secret manager.
6. On every commit github send webhook to jaas jenkins.
7. Jenkins pipeline is triggered and run it's logic when commit changed any file under path with secret event files.
8. Pipeline read a secret name and gcp path of secret requiring update.
9. Pipeline fetch secret from GCP secret-manager.
10. Pipeline update a secret value in Jenkins credential store in administration folder.
11. Old versions of secret are cleaned by existing cleaner component.

During first two days of test we found that our cleaner is not able to clean properly secrets rotated every hour. A cleaner remove old keys only when they are 24 hours stale. Because hourly rotated keys didn't meet this requirement, they were not removed. This caused hit limit of count of service account active keys and stopped rotation. To workaround this limit a rotation period for test secret was set to 3 hours. With longer interval we should be below 10 keys limit for service account for 24hours rolling window.

**Comment by Ressetkk** [comment]
Yeah, the concept sound to be working good already. However, I'm still not bought by a concept of using git as source of truth. Here's my concerns:
1. It introduces a middle external service that is out of the scope of us
2. It's much harder to debug, because if something breaks you have to look at 
  * GCP PubSub logs
  * Both of the CloudRun logs
  * Secret Manager logs
  * CloudRun -> GHE integration
  * GHE -> Jenkins integration
  * Jenkins logs itself
3. You can't can't guarantee that this will work in an uninterrupted way. There might be some connection issues between either of the services. Routing errors, TCP errors might happen. And this may look good on either side, but in fact may be broken
4. That's relatively a lot of stuff to maintain and take care of. Having yet another CloudRun, PubSub topic, git repository and entire Jenkins script just for one feature seems a little overkill for me.

What I would see the process of rotating is something like that:
1. Secret Manager requests a rotation
2. Existing cloud function picks it up and rotates the secret
3. Jenkins job that runs let's say every hour polls the Secret manager and checks if there are any updates to the secret
4. If there are any, updates the secret

I just see no sense in having this sophisticated functionality just for secret rotation. I understand that in the future *we may* have a need to somehow run internal workloads on OSS changes, but I'm certain we will find a suitable solution when the time comes.

@tobiscr please get familiar with the discussion and raise your comment. It'd be very, very helpful to see your view on that topic.

**Comment by dekiel** [comment]
At. 1 Why this is a problem? We use plenty external services. Is this middle external service not reliable? Is it not supported? Do you have any data to point this might be a problem or it's just  your personal preferences?
At 2. With your steps you could remove:
  - cloud run -> ghe integration
  - ghe -> jenkins integration
But you will add:
  - jenkins -> secret manager integration
Other points remain the same.
With all components logging to one location a debug will not be a problem and logging in one location is a requirement for any scenario.
At. 3 With your steps you can't guarantee this too. You will have same failing points. This point is not valid.
At. 4 There is no separate repository, there is no separate pubsub topic, there is always need to have something run on Jenkins, even with steps you proposed there is a need to run a script on Jenkins. This point is not valid.

The approach you proposed.
1. Will increase load on Jenkins. We would run the script every hour even if there is nothing to update. This script will have to check all secrets in secret manager if they have a new version added on every run. Having rotation for service accounts set to every 85 days that is a plenty script execution and API calls just to confirm nothing to rotate. It's simply burning a money.
2. It will add a one hour delay in rotating a secrets. In case compromising a key we will have to trigger an update manually otherwise other workloads on Jenkins using a compromised key will break for one hour in worst case.
3. We already have a need to run internal workload on OSS change.

We have access to Google services APIs which are reliable. Our GHE instance doesn't have downtimes too. A GH webhook mechanism is very well tested and widely used in our organisation. We can have an elegant, fast, scalable, modern, microservice based, event based solution. Why we should not take it? Because of need to check a logs of one cloud run instance more?

**Comment by Ressetkk** [comment]
1. Running simple script that runs for several seconds will *not* increase Jenkins workloads at all. Those take very little CPU time and disk space. Load will not be even noticeable. If you want to talk about money, then it is included in Jenkin's price, since the instance doesn't scale.
2. In my opinion there is literally no need to be strict with secret rotation time frames. Having an ~hour of time between switching secrets is by far an acceptable approach. There will be a rotation in place, it should be safe enough. You can either adjust the key cleaner, so it cleans keys older than delta time needed for grace clean period. At most there would be 2 keys active for at most an hour.
3. Sure, but it is related to release and not to security-critical stuff.

My point is, Secret rotation should be as simple as possible, so there are as little breaking points as possible. Usually such mission-critical stuff like secret rotation are handled in direct event-based way, or by polling the upstream service for updates. Instead of relying on complex approaches, which indeed will work, but will require quite a lot of work, maybe there should be a way to make it simpler? Simply polling a service should be sufficient and way simpler to configure.

**Comment by dekiel** [comment]
At. 1 Running script will use CPU and other resources. Saying it will not increase load is **NOT A TRUE**. If we will have more and more such small scripts running every minute, hour we will have to go for bigger Jenkins instance. Saying that running some workload cost nothing is simply **NOT A TRUE**. Same for API calls to secret manager. They cost too.

At 2. In my opinion there is a need. Having such delays makes maintaining harder. In case security breach you have to deal with delay outside a system. Another condition to remember and support. Cleaning is another topic which I didn't touch in POC. I'm reusing existing approach.

At 3. But it is. You wrote there is no need to find a solution. This is **NOT A TRUE AGAIN**.

> Usually such mission-critical stuff like secret rotation are handled in direct event-based way, or by polling the upstream service for updates. I've never seen any service that takes care of secrets in this way you proposed. Instead of relying on complex approaches,

Could you please provide example of service implementations you refer too.

Using a github as a proxy is not a complex solution. Building solutions as simple as possible doesn't mean this will be best solution. Taking shortcut is straight way to getting a technical debt with which the team will have to deal later.

Again do you have any hard data to prove this will not work or cause issues? You asked for POC saying this will be not reliable. A POC proved a solution is reliable. Now you saying it's to complex. How we measure complexity? How complexity measure related to other measures and requirements?

**Comment by tobiscr** [comment]
I also agree with @Ressetkk that the solution has a higher complexity as a pure pull approach within Jenkins.

But I also agree with your arguments that

1. the pull appraoch is much more resource intensive and not scaling (adding more systems which have to rotate secretes could lead to an overload of the secret manager)
2. in Jenkins is usually Groovy required to interact with the secret store - this would lead to use another programming language which is not known by the team and hard to maintain

**Comment by Ressetkk** [comment]
Sure, let's argue about the fractions of CPU time for a script that can run as simple cron task and will barely be even noticeable from instance perspective.

I'm afraid to say that 20-liner script written in Groovy will not be a huge addition to the technical debt we already have. This is case only for Jenkins. There is no need to build a complicated stuff just only for one instance which will eventually get removed.

@tobiscr I think that we should estimate the cost of both approaches and which would be easier to implement and maintain.

**Comment by dekiel** [comment]
So arguing about checking logs in one cloud run is better? Especially these logs will be stored along with other.

**Comment by tobiscr** [comment]
@Ressetkk : I doubt that 20lines (it depends how "nice" you want to have it.. but I would expect 200-400 lines) for this feature will be enough in Groovy as interacting with the credentials store needs some boilerplate code.

But I think the amount of lines is here not the challenge, it's more the increase of complexity / learning efforts caused by adding another programming language in place.

As said - I'm not the one who is enabled to make the final technical decision. That should be made by the team - I can ony support in making the decision as objective as possible.
