### ISSUE TITLE
Periodic job that checks if values.yaml uses up-to-date Kyma components version

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/test-infra#588]
When the developer modifies Kyma components, he needs to do 2 PR:
- introduce changes in the component
- bump component's image version

It can happen that he/she forget to bump image version and such a situation can be detected only when doing a release of the Kyma.

AC:
- assure convention naming for version in values.yaml
- add information about module in a given component
- skip alert if versions don't match, but only documentation was changed
- throw alert only if version don't match longer than 3 (configurable). Job runs every day.
- implement a periodic job, that is executed once a week (for example on Monday morning). This job compare component's version used in values.yaml and git commit id for components directory. In case there is a difference, job should fail, report which components are outdated and send slack notification.
- follow up task to automate release bumping

**Comment by adamwalach** [comment]
- [ ] define convention for versions in values.yaml and add information about module in a given component in Makefile
- [ ] create a golang app (in test-infra/development/tools) to list components that are out of sync
- [ ] create periodic job

**Comment by jasiu001** [comment]
**Components**

| component | Makefile command | values.yaml structure | comments |
| --- | --- | --- | --- |
| components/api-controller/Makefile | | |
| components/apiserver-proxy/Makefile | | |
| components/application-broker/Makefile | | |
| components/application-gateway/Makefile | | |
| components/application-operator/Makefile | | |
| components/application-registry/Makefile | | |
| components/asset-upload-service/Makefile | | |
| components/configurations-generator/Makefile | | |
| components/connection-token-handler/Makefile | | |
| components/connectivity-certs-controller/Makefile | | |
| components/connector-service/Makefile | | |
| components/etcd-backup-job/Makefile | | |
| components/etcd-tls-setup-job/Makefile | | |
| components/event-bus/Makefile | | |
| components/event-service/Makefile | | |
| components/helm-broker/Makefile | | |
| components/installer/Makefile | | |
| components/istio-kyma-patch/Makefile | | |
| components/k8s-dashboard-proxy/Makefile | | |
| components/namespace-controller/Makefile | | |
| components/service-binding-usage-controller/Makefile | | |
| components/xip-patch/Makefile | | |

**Tests**
| component | Makefile command | values.yaml structure | comments |
| --- | --- | --- | --- |
| | | |

**Tools**
| component | Makefile command | values.yaml structure | comments |
| --- | --- | --- | --- |
| | | |

**Comment by sjanota** [comment]
Question: what about images that needs to be bumped along with some changes in charts? If image is bumped automatically it would break master. 

I don't think automatic bumping is right approach, it is hiding complexity behind our process and may introduce broken master. I would go completely different way and disable building new images on release. This way developer has perfect control over what gets released vs what doesn't.

I have a real use case behind it from current release. In order to prepare a release release branch was created on Friday.  Same day earlier changes in code were merged. Those changes required also modifications in chart, which were not merged yet, because of infrastructural problems. 
1. Release branch failed because new image was created and was not compatible with charts.
2. If we had automatic bump of image on Monday this would break master and stop whole development.
3. The only reasonable solution for me is not to automatically build and bump anything. In this scenario rc1 would be created without problems and new image would arrive in rc2.

**Comment by PK85** [comment]
Hi Szymon,

that ticket is about showing differences between versions of components and images versions used in charts on master branch. Your concerns and case about automatic bumping are not about that ticket.

Cheers, PK

**Comment by aszecowka** [comment]
@sjanota 
We need to understand why we want to bump all images in the release version. When releasing, we want to be sure that what we have in the code, the same we have in running cluster. 
Automatic bumping is planned for the release branch, not for the master. Regarding your example, we should just avoid the situation that we make incompatible changes in our components when we know that release is around the corner. 
Last but not least, having "release" version of images has an additional advantage: if there will be additional requirements for release images (like additional security scanning), we have our infrastructure already in place.

**Comment by sjanota** [comment]
@PK @aszecowka Thanks for clarification. All my concerns have vanished 😄
