### ISSUE TITLE
Implementation for code scanning tools - Fossa

### ISSUE THREAD

**Issue by kubadz** [kyma-project/test-infra#606]
@kubadz commented on [Mon Feb 11 2019](https://github.com/kyma-project/kyma/issues/2699)

**Description**

One of two tasks from Epic #589.

AC: 
Fosa should be run on every PR

**Comment by Demonsthere** [comment]
@jose-cortina @crabtree After a discussion with @aszecowka we came to a conclusion that running fossa on every pr for the whole kyma project will be too much time and resource consuming. Moreover, running fossa as a separate task is also not optimal, as the scan requires to compile (and therefore perform a `dep ensure`) each application it checks, which is already performed in the component tasks. 
Suggested solutions:
- Create a dedicated ProwJob for each component that needs to be scanned:
  - We duplicate the vendoring and compilation stage
  - We have a separate and dedicated job with the scan report
  - The task can be set as optional in prow
- Modify the `build.sh` to perform the scan:
  - We avoid all duplication, but attach the scan to component building.
  - The scan report would be mixed with component building logs
  - Should the scan decide if the build fails?

@jose-cortina @crabtree @aszecowka Please write any additional comments in this thread

**Comment by aszecowka** [comment]
I like the approach with the modification of build.sh because it is the simplest one. Maybe we can run this scanning tool only for a Postsubmit job for a component and for release jobs? For a time being, we can mark in the script that failing of the scan does not break the build and later make it "required".

**Comment by jose-cortina** [comment]
From the compliance side we just need to make sure that we do not produce a release that has any issues, so that means to me that when the tools find an issue this must stop the CI / Release plan (wherever this is running). This is then of course done with no manual intervention ;-)

This then means that from my perspective both options are OK, provided the above is enforced.

An important point is to document the process, including for example what happens when there is a new component or some components are deprecated, changed, etc, so that we also have a way to ensure we cover all relevant components.

**Comment by Demonsthere** [comment]
After investigating the tool for some time, I think that we cannot use it in a on PR format: 
- As our code is monorepo, Fossa included everything into a single project (as in git project repo)
- If we want to run it per PR, per component, each run is seen as a new run for the whole project, and not as a separate instance
- We can run analytics on PR, per component. However the analytics cli binary sends the data to Fossa server, where it is processed. In order to have a passed/not-passed scenario we would need to get some status after the data has been processed.

**Comment by Demonsthere** [comment]
Update:
After some talks, we have come to a conclusion that implementing Fossa on PR seems like a bad idea, and the current level of integration (after push to master) seems sufficient. We only need to add Fossa badges to the README of our projects, however I don't have access to do that.
