### ISSUE TITLE
kaniko-build: provide multi-arch builds

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/test-infra#6077]
@kyma-project/cmp has a hard requirement for building multi-arch builds for local development. Kaniko doesn't support building multi-arch builds, because it is working inside a container, so the architecture is assumed based on the system container is running on. We have to find a way to provide building multi-arch builds in our CI.

~~One of the ideas is to adopt latest version of `img`, as it works as a drop-in replacement for `docker build` without the need of using privileged containers.~~

~~We can provide experimental functionality of `img` with flag `--use-img` to kaniko-build to use it as backend. Frontend, config-based configuration and tag assumption will not change at all. That will require to install additional binaries:~~
* ~~img v0.5.11~~
* ~~qemu~~
* ~~qemu-system~~

~~img will greatly reduce the build speed, so it should be considered as experimental feature~~
`img` is not maintained well. Better alternative is to use BuildKit directly.

My suggestion is to add additional [BuildKit](https://github.com/moby/buildkit) build backend, alongside kaniko to `kaniko-build`. By default kaniko-build will use kaniko, but it will be possible to switch to BuildKit using env variable `USE_BUILDKIT=true`.

This means we have to provide separate image with buildit backend, embedded environment variable to avoid confusion and modified kaniko-build binary as entrypoint. 

The image itself with proper pod configuration gives good results as fast experimental feature for now. It also supports multi-arch, daemonless and rootless builds by default.

**Comment by Halamix2** [comment]
As a drop-in replacement it should be easy to implement

For img and kaniko integration we could check if the target arch is different than native one and run either kaniko or img based on that, not reducing speed of native builds

**Comment by Ressetkk** [comment]
I managed to reproduce the build with rootless container, but I'm still struggling with achieving multi-platform builds. There is still more on-going work to do.

**Comment by dekiel** [comment]
Requirements and acceptance criteria for this solution are the same as earlier for gcbuild or kaniko.
What I understand from discussion is that our tool kaniko-build will call buildkit binary instead kaniko binary within a docker container. If that is the case then we should meet all requirements we defined earlier.
We should change a name of a tool from kaniko-build to something generic, because we will use not only kaniko.
I don't understand comment about flags.
1. Flags of which tool we will parse? If we will use renamed kaniko-build as a frontend, we need to parse kaniko-build flags and translate them to buildkit flags. Right?
2. Why you mention buildctl? Will we call buildkit binary or buildctl binary?

**Comment by dekiel** [comment]
Please link this issue to the parent one which contain all steps and represent the overall implementation status.
