### ISSUE TITLE
Tracing tests failing: Cannot get jaeger trace

### ISSUE THREAD

**Issue by adityabhatia** [kyma-project/test-infra#6129]
**Description**

Tracing tests are failing in 2 pipelines:

https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-k3d-kyma2-to-main
https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main-reconciler-main

**Expected result**
Traces tests should not fail

**Actual result**
Tracing tests are failing

**Steps to reproduce**
Example runs:
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-k3d-kyma2-to-main/1577297497229889536
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main-reconciler-main/1577297497158586368

**Comment by k15r** [comment]
the issue is a result of a change in the serverless component. Functions will not be rebuilt during the upgrade, but the environment variables used for their configuration will change. This causes the tracer for the node runtime to fail. 

An easy fix would be to rebuild the function image during the cluster upgrade.

**Comment by kwiatekus** [comment]
caused by https://github.com/kyma-project/kyma/issues/15790
