### ISSUE TITLE
Tests executed in buildpack-golang-kubebuilder are failing

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/test-infra#645]
**Description**

Tests that use kubebuilder sometimes failing because kubebuilder is not able to start `controlplane`. 
Failed execution: https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/2823/pre-master-kyma-components-assetstore-controller-manager/1098492589587304448/build-log.txt

The problem doesn't occur on the local machine, only in buildpack.

**Expected result**

Tests that use Kubebuilder should be stable.

**Actual result**

API tests sometimes failing because of problems with Kubebuilder.
```
2019/02/21 08:04:53 failed to start the controlplane. retried 5 times
```

**Steps to reproduce**

Execute build of `assetstore-controller-manager`

**Troubleshooting**

**Comment by michal-hudy** [comment]
It looks like jobs that uses this buildpack needs more resources:
![image](https://user-images.githubusercontent.com/26445970/53228610-050e9180-3682-11e9-974b-7f32d438e137.png)

Our standard golang job uses 2Gi of memory and 1.5 CPU

**Comment by michal-hudy** [comment]
Jobs needs more resources

**Comment by pkosiec** [comment]
Unfortunately it still occurs. After doing some changes to the assetstore, three builds in row failed because of the error. Fourth passed:

https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/2928/pre-master-kyma-components-assetstore-controller-manager/1101552755568283648/build-log.txt
https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/2928/pre-master-kyma-components-assetstore-controller-manager/1101555776347967488/build-log.txt
https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/2928/pre-master-kyma-components-assetstore-controller-manager/1101557034064547840/build-log.txt

**Comment by michal-hudy** [comment]
According to discussion on Kubernetes slack, we should update dependencies - it may help:
![image](https://user-images.githubusercontent.com/26445970/53720277-9c34cf80-3e60-11e9-96a0-3369d5d21f9d.png)

https://kubernetes.slack.com/archives/CAR30FCJZ/p1551112489031400

**Comment by michal-hudy** [comment]
It is still valid

**Comment by michal-hudy** [comment]
The jobs fail because ETCD didn't start in the 20s. Since `controller-runtime` 0.1.5 it is possible to configure timeout by envs:
 - `KUBEBUILDER_CONTROLPLANE_START_TIMEOUT`
 - `KUBEBUILDER_CONTROLPLANE_STOP_TIMEOUT`
