### ISSUE TITLE
[Security] Remove security context: priviledged from k3d prow job template.

### ISSUE THREAD

**Issue by KacperMalachowski** [kyma-project/test-infra#6607]
**Description**

We don't want to run containers in privileged mode by default, so we have to remove that context from templates.

**Comment by Ressetkk** [comment]
Firstly we have to make sure wether we really need to remove privileged security context. Keep in mind that one of the requirements that Prow's images have to meet is that we either remove privileged context **or** ensure test images have no High CVEs.

By removing privileged context completely, you also lose access to use Docker daemon, K3d, kind and other workloads that need Docker daemon to run. I know we resolved Docker image building by introducing image-builder, but there are other use-cases that are quite complicated, like using K3d in VM through SSH, where simply spinning K3d inside a pod would make developer's life much easier.

Maybe the requirement should be changed and just ensure our test images are always vulnerability free, as stated in #6793

cc @tobiscr @dekiel
/remove-lifecycle stale

**Comment by dekiel** [comment]
We should test usage of privileged mode and prevent using it when not accepted. We should definitely remove setting it to true in rendertemplates globalSets. Using privileged mode should be explicit if really needed. If we decide we don't need it for any workload it should be removed from template completely.

As far I know for now there is no hard requirement for using it in any prowjob. A k3d usage is something what requires evaluation and discussion. Maybe an exception is a solution in this case.

In terms of allowing privileged containers because we test our images, in my opinion that requirement is much more complex than running regular tests. It requires a solution preventing vulnerable images on k8s cluster, when deployed and already running on cluster. We don't have any tool for that.

**Comment by tobiscr** [comment]
Obsolete as we decided to allow the execution of k3d within Prow jobs and OPA Gatekeeper will take care about security related baselines.
