### ISSUE TITLE
Enable developer access to test clusters for easier installation failure analysis

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/test-infra#740]
**Description**

Currently, reasons for installation failures on our test clusters (like gke-int-pr...) are mostly unknown.
Kyma Installer doesn't know (and can't know) reasons for a failure of a certain Helm release. Even Helm itself doesn't know - or doesn't care -  real causes of Pod crash are usually hidden in Pod's logs.
Additionally, releases not always fail due to Pod crashes.
Everything that can't be provisioned by Helm due to conflict or lack of depending resources causes Helm to wait until the release is timed-out and the installation crashes.
You could dump Helm status for a release, but it's not enough - developer will know the resource that caused time-out, but the real cause of a deadlock requires careful inspection of the cluster state.

I suggest allowing developers to get access to test clusters, along with extending test clusters lifetime beyond test job time. Reasonable time is about an hour. 
This allows developers to access test cluster and manually find the root of the problem.

Security of the solution is important. Only PR author should be able to access the test cluster. Impact on other clusters must be minimized. Access level should be read-only and perhaps restricted only to certain namespaces.

**Comment by Demonsthere** [comment]
In the SIG-Deploy-CI meeting we discussed this topic and came to the conclusion that providing access is not a thing that we want enable. We rather should enable you to see the logs, by offering them in the build results.
This is because the prowjobs are blocking, meaning you cannot merge a PR before all prowjobs complete and succeed. Providing access would require to either detach the clusters or increase their TTL, wich would in turn increase costs and time required for PRs to be merged.
