### ISSUE TITLE
Have one-click release process

### ISSUE THREAD

**Issue by sayanh** [kyma-project/test-infra#742]
**Description**

Current release [process](https://github.com/kyma-project/community/blob/master/guidelines/releases/release-process.md) is tedious and error prone.

Design a completely new and fully automated release process.

**Comment by aszecowka** [comment]
Definitely release process is not yet finished and requires a lot of improvement but IMO we don't need to create a completely new process. Here you can find my **private** list of items that move our release process to the next level:
- most boring and error-prone part is to update all kyma-specific images to use release version (for example 0.8.0-rc1). This can be automated, and first part is almost done: https://github.com/kyma-project/kyma/pull/2850
In Makefile, we are going to add a new target, which provides information in which chart given component is used. If we have that information, we can easily provide a tool that modifies proper values.yaml with the release version. 
If this will be automated, we solve hmost of the problems IMO. But we can go even further:
- currently, some jobs needs to be triggered manually. It is done in this way, because they depends on other builds. In Prow is not possible to define complicated workflows. But we can use Prow and Knative Build AFAIK to achieve such functionality. Knative Builds can be also helpful in normal development against master branch, where we have to always create 2 PR: one to update code of the component, and another one to update chart where this component is used. So we can kill two birds with one stone.
- Before we create release we should provision cluster with new version of Kyma to allow all teams double-check if all their functionality works. Currently, you have to do it manually. Gophers plan to implement on demand clusters in the next sprint and thanks to that, we can automate also that.

**Comment by kasiakepka** [comment]
This concept has to be reviewed as there is a lot of activity going on around release process:
https://github.com/kyma-project/community/issues/339
https://github.com/kyma-project/kyma/issues/5460
See also #kyma-relase Slack channel

**Comment by kasiakepka** [comment]
We plan to:

reduce manual steps to minumum
enable releases on demand

**Comment by adamwalach** [comment]
It works with a github actions: https://github.com/kyma-project/community/blob/main/docs/guidelines/releases-guidelines/02-kyma-release-process.md#create-a-release
