### ISSUE TITLE
Integration job on GKE fails in DNS removal phase

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/test-infra#770]
**Description**

`post-master-kyma-gke-integration` jobs keep failing in the `Delete Remote Environments DNS Record` phase:

```
Mon Mar 18 10:04:45 UTC 2019
--
683 | Transaction started [transaction.yaml].
684 | Record removal appended to transaction at [transaction.yaml].
685 | ERROR: (gcloud.dns.record-sets.transaction.execute) HTTPError 412: Precondition not met for 'entity.change.deletions[0]'
686 | Aborted transaction [transaction.yaml].
687 | Unable to delete DNS record, let's wait 5 seconds and retry. Attempts 1 of 3.
688 | Transaction started [transaction.yaml].
689 | Record removal appended to transaction at [transaction.yaml].
690 | ERROR: (gcloud.dns.record-sets.transaction.execute) HTTPError 412: Precondition not met for 'entity.change.deletions[0]'
```
Here is a sample job: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-integration/1107566886209458176

**Comment by Demonsthere** [comment]
Probable reason for this behaviour:
We know that the Changes API in GCP can handle only one request at a time, and because of this, we have added a retry mechanism in the creation/deletion scripts.

However, this still fails in some of the cases. This is probably due to a race condition if several jobs are running at the same time. 

Suggested solution:
Increase the retry count and randomise the waiting period between retries

**Comment by michal-hudy** [comment]
@Demonsthere Is this limitation of GCP API somewhere documented?

Did anyone check the content of `transaction.yaml`?

I really don't like the idea of increasing attempts. It only hides the real problem. Now is 3, we will change it to 10, later it will be 20...

**Comment by jesusreal** [comment]
Happened again on 28th March for job _kyma-aks-nightly_. See logs: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-aks-nightly/1111251970213023744

**Comment by jesusreal** [comment]
Same issue happened on 28th March for _kyma-load-tests-weekly_ job. See logs [here](https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/kyma-load-tests-weekly/1111297143328477184)

**Comment by jesusreal** [comment]
Same issue happened on _post-master-kyma-gke-integration_ on 1st April: https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-integration/1112605248016355328

**Comment by tehcyx** [comment]
Linking https://github.com/kyma-project/test-infra/issues/829 which will implement changes for IP and DNS cleaners.

**Comment by adamwalach** [comment]
This issue is still present:
![Screenshot 2020-05-27 at 12 25 51](https://user-images.githubusercontent.com/8530211/83008307-42946400-a015-11ea-9a59-1c181b21f159.png)

**Comment by Ressetkk** [comment]
For what I've gathered so far:
Everytime the transaction is started the `transaction.yaml` is generated with the update of a SOA record with incremented SERIAL field. According to the [SOA record wiki page](https://en.wikipedia.org/wiki/SOA_record) "If a secondary name server slaved to this one observes an increase in this number, the slave will assume that the zone has been updated and initiate a zone transfer." So it is needed to update SOA record during every DNS update.
Below is a sample yaml generated by `cloud dns transaction start --zone ZONE`:
```yaml
---
additions:
- kind: dns#resourceRecordSet
  name: XXX
  rrdatas:
  - ns-cloud-b1.googledomains.com. cloud-dns-hostmaster.google.com. 76286 21600 3600
    259200 300
  ttl: 21600
  type: SOA
deletions:
- kind: dns#resourceRecordSet
  name: XXX
  rrdatas:
  - ns-cloud-b1.googledomains.com. cloud-dns-hostmaster.google.com. 76285 21600 3600
    259200 300
  ttl: 21600
  type: SOA
```
The script is sometimes failing on executing deletion of a SOA record. I assume that this happens when multiple jobs try to execute DNS update at the same time and the SOA record is either invalid or not present, because it has been updated before by different job/manually from GCP UI.

I think the real solution would be to increase the retry count and timeout for updating DNS zone inside a job.
