### ISSUE TITLE
[Istio] Release pipelines

### ISSUE THREAD

**Issue by strekm** [kyma-project/test-infra#7761]
**Description**

Based on Kyma project requirements and internal design implement all jobs that should be run on Istio module release. Mandatory jobs should stop github release. Jobs should be triggered by tag creation on release branch. Jobs should be owned by goats team, should have proper description and self-explanatory name. 

DoD:
- [x] jobs implemented
- [x] execution of pipeline should result in GH release of Istio module
- [x] Github release should contain manifest to deploy operator and default Istio CR (decision in [issue #792](https://github.com/kyma-project/community/issues/792))
- [x] GH release should contain changelog and RN (generated from docs/release-notes)
- [x] jobs are owned by goat
- [x] Istio is part of job name
- [x] jobs have defined description 
- [x] Release documentation (like in api-gateway) exists

**Attachments**
part of: https://github.com/kyma-project/istio/issues/38

**Comment by strekm** [comment]
add RN to DoD. If needed RN is part of developed feature, which means it lands on main branch

**Comment by triffer** [comment]
We should have a straightforward and simple release process as our focus on a release pipeline has changed with the abandonment of Tekton. We also want to be able to release at any time, that means critical tests should already be executed on PR or main.

We keep the creation of the release branch in the process so that we can easily create patch releases at any time.

## Prow-based release process
- Create a release branch in the format of `release-x.y` in the repository.
- Create a tag triggering the execution of a Prow release job. Prow job config should have branches configured like the following:
  ```yaml
  branches:
    - ^\d+\.\d+\.\d+(?:-.*)?$
  ```
- The prow job 
  - builds the module
  - builds the operator
  - creates a GitHub release with the release artifacts and release notes
  
## Release notes
### File-based
During the planing we discussed that we will store the release notes in the folder `docs/release-notes`. We could use a file with
the name in the semantic version format of `major.minor.patch` for each release. 
Since release notes don't need to be historically coupled to the code, it's arguable if we should store them in the repository at all.

### PR-based proposal
During the discussion with Kamil another solution was proposed, which is to store the Release Notes in the PRs.
We already discussed this partly in the planing, but the approach would be different by having a separate field in a PR where release notes would be.
You can see an example of the `Does this PR introduce a user-facing change?` field in a [PR to the kubernetes repo](https://github.com/kubernetes/kubernetes/pull/118658).
We could then use the Prow `release-note` plugin to block PRs that have a specific label, e.g. feature, but don't have a release note in the PR.
A script would then be able to fetch all release notes from the PR during a release.

## Alternative release process having Prow jobs controlled by GitHub Actions
Since other teams are using GitHub Actions for their release, I also thought about a process using pipelines in GitHub.
Following this process we would be able to run multiple Prow jobs in parallel and have a PR to control them.
Since this is far more complex than the Prow-based release process, I wouldn't implement it for now since we don't have the requirement as clear. 
But I wanted to document it here for discussion and future reference.

- Creating a release branch in the format of `release-x.y` in the repository
- Trigger a GitHub Action manually by providing the version of the new release in semantic format, e.g. `0.1.0`. To make it more bulletproof, we can also just use the patch level as input,
  since we can derive the major and minor versions from the branch name.
  - This GitHub Action will
    - Verify that release notes exist for the given version
    - Create or update a file named `VERSION` in the root of the project with the given version. This is used as the trigger/change to create a PR. 
      This can be a temporary file only existing in release branches, It's created on initial release in the branch and updated on patch releases.
    - Create a PR to the release branch with the updated `VERSION` file
- The PR creation will trigger the relevant release prow jobs, for now it's building the operator and module
- If all status checks in the PR are passed a GitHub Action will be triggered
  - This GitHub Action will
    - Create a git tag for the release
    - Create a GH release with release artifacts and release notes

## Additional clean up of Prow jobs
To get our Prow configuration in a good shape we should additional:
- [ ] Remove the jobs `pull-istio-operator-integration-k3d` and `post-istio-operator-integration-k3d` since they are not executing any tests
- [ ] Restructure our Prow jobs to be in one folder (`prow/jobs/istio`)

**Comment by barchw** [comment]
- https://github.com/kyma-project/istio/pull/189
- https://github.com/kyma-project/test-infra/pull/7962

**Comment by barchw** [comment]
Release guideline PR was moved to internal repository
