### ISSUE TITLE
Configure redirection to https

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/test-infra#85]
**Description**

Configure redirection to `https` for `status.build.kyma-project.io`.

AC:
 - [x] http://status.build.kyma-project.io should return `HTTP 301` code and points to https://status.build.kyma-project.io

**Comment by Demonsthere** [comment]
Wouldn't it be enough to set `ingress.kubernetes.io/force-ssl-redirect: "true"` annotation on the ingress object?

**Comment by Demonsthere** [comment]
I see the problem here, the GCP ingress [does not support redirection](https://github.com/kubernetes/ingress-gce#ingress-cannot-redirect-http-to-https), however we can:
- Block http traffic (this causes http to return `HTTP 404`)
- Change our ingress controller to the basic `nginx-ingress`, which supports redirections
- Create a nginx proxy in front of deck and hook to support redirection

**Comment by Demonsthere** [comment]
UPDATE:
https://github.com/kyma-project/test-infra/pull/185#issuecomment-446909045

**Comment by Demonsthere** [comment]
The change is done as a patch to the deck deployment because if I would modify the `starter.yaml` we would have the situation in which someone who created a fork cluster and went to https their dashboard, would be redirected to our production dashboard. This avoids this situation as we run the patch only on our prod setup and not for development ones.
