### ISSUE TITLE
[Feedback from devs] Remove Neighbors ownership from other teams prowjobs.

### ISSUE THREAD

**Issue by dekiel** [kyma-project/test-infra#8563]
At present neighbors github team `prow` is an owner of almost all directories under `prow/jobs` directory containing prowjobs definitions. Additionally `prow` team is an owner of all data files under `templates/data` directory. Effectively that means any change in prowjobs definitions requires neighbors team approval, even if the changed prowjobs are completely owned by other teams.

This is causing the neighbors team to be a bottleneck for other teams. Moreover, for many of these changes the neighbors team doesn't know enough context to provide valuable review.

Historically this ownership was setup as a security gateway to control usage of some sensitive data. Currently control to sensitive data is provided by OPA gatekeeper.

Neighbors team `prow` group should be set as owner only for it's own prowjobs and data files.

AC:
 - [x] Use metadata inside of Job-definition files to identify the owner of the job and group all jobs by their owner (e.g. by teams- or component-name).
     - [x] If a directory includes only jobs owned by the same team, the whole directroy will be owned  by this team
     - [x] If a directory includes jobs owned by mulitple teams, define the ownership per job-file
 - [ ] Update the code-ownership file to make the particular team to be owner of their dedicated job-description files/directories
- [ ] Remove the code-ownership of Neighbors from any directory which doesn't include jobs related to the Neighbors team
- [ ] If this code ownership-update will not break the requirement for the review, we remove the ownership from the template/data-directory

**Comment by Ressetkk** [comment]
Prow team should be maintainers of the entire repo in case if they need to do some usual plumbing stuff or maintenance so they don't ask other people for review and approval. However they should not be asked to review. That means we still are the owners of all directories, but if there are changes to the specific files in designated directory, only its owners are asked. Without this we will always be blocked by external code review when we need to add/remove some fields in the jobs even if it should not be bothering the devs or some automations will not be possible to introduce in the repo without relying on hacky solutions (and IMO that is not a good approach to design robust applications).

AFAIK this can't be done with GitHub's CODEOWNERS feature. It doesn't respect the tree structure of the repository and actually excludes the root maintainers from being the owners for subdirectory, if it contains its own list of owners. We can't modify how the CODEOWNERS are working.

Additionally we should think if it's a good option to remove the write access from test-infra from other members besides Prow team. I see that some people use GitHub UI to change files. That creates branches in the upstream without cleaning them afterward, because the branches by default drop into the GitHub's branch protection rules and without actual admin intervention it's not possible to clean it up. By removing write access you actively enforce on contributors to use their own forks to make PRs, even if they use GitHub UI.
